/**
 * PII mask audit: what personal information in a real uploaded resume reaches
 * the model provider? See audit-core.js for what is measured and how.
 *
 * Two scenarios per resume, plus two cross-checks:
 *   guest      no account: the mask has patterns and the CV's own name
 *   account    logged in, with the account row from the corpus as identity
 *   DOCX guest the same resume as a Word file
 *   redactor   if the model echoed the whole CV back, what the inbound
 *              redactor would catch
 *
 * Run: npm run pii-audit --prefix server            (corpus + holdout)
 *      node server/scripts/pii-audit/run-audit.js --holdout
 * Writes: docs/samples/pii_corpus/results.json, RESULTS.md, outbound/<id>.txt
 */

import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { CORPUS, CATEGORY_LABELS } from './corpus.js';
import { HOLDOUT, HOLDOUT_BD } from './corpus-holdout.js';
import { auditEntry, CORPUS_DIR } from './audit-core.js';

const ONLY = process.argv.includes('--holdout-bd') ? 'holdout-bd' : process.argv.includes('--holdout') ? 'holdout' : null;
const SET = { 'holdout-bd': HOLDOUT_BD, holdout: HOLDOUT }[ONLY] ?? [...CORPUS, ...HOLDOUT, ...HOLDOUT_BD];
const SUFFIX = ONLY ? `-${ONLY}` : '';
const OUTBOUND_DIR = path.join(CORPUS_DIR, 'outbound');

/* ── Report ─────────────────────────────────────────────────────────────── */

const SCENARIOS = ['guest', 'account', 'docxGuest', 'redactorOnEcho'];

function tally(results) {
  const byCat = {};
  for (const r of results) {
    for (const item of r.items) {
      const cat = (byCat[item.cat] ??= Object.fromEntries(SCENARIOS.map((s) => [s, { masked: 0, partial: 0, leaked: 0, absent: 0 }])));
      for (const s of SCENARIOS) cat[s][item[s].status] += 1;
    }
  }
  return byCat;
}

const pct = (n, d) => (d === 0 ? '—' : `${Math.round((100 * n) / d)}%`);
const cell = (t) => {
  const judged = t.masked + t.partial + t.leaked;
  return `${t.masked}/${judged} (${pct(t.masked, judged)})${t.partial ? ` · ${t.partial} partial` : ''}`;
};
const mark = { masked: '✅', partial: '🟡', leaked: '❌', absent: '⚪' };

function renderMarkdown(results) {
  const byCat = tally(results);
  const lines = [];
  lines.push('# PII mask audit — raw results');
  lines.push('');
  lines.push('Generated by `node server/scripts/pii-audit/run-audit.js`. The analysis is in `docs/qa/PII_MASK_AUDIT.md`.');
  lines.push('');
  lines.push('Each cell is items fully masked / items present in the extracted text. ✅ masked · 🟡 partly masked (some name words left) · ❌ leaked · ⚪ not in the extracted text, so not judged.');
  lines.push('');
  lines.push('## By category');
  lines.push('');
  lines.push('| Category | PDF, guest | PDF, logged in | DOCX, guest | Inbound redactor, if the model echoed it |');
  lines.push('|---|---|---|---|---|');
  for (const [cat, label] of Object.entries(CATEGORY_LABELS)) {
    const t = byCat[cat];
    if (!t) continue;
    lines.push(`| ${label} | ${cell(t.guest)} | ${cell(t.account)} | ${cell(t.docxGuest)} | ${cell(t.redactorOnEcho)} |`);
  }
  const total = (s) => Object.values(byCat).reduce((acc, t) => {
    for (const k of Object.keys(acc)) acc[k] += t[s][k];
    return acc;
  }, { masked: 0, partial: 0, leaked: 0, absent: 0 });
  lines.push(`| **All** | **${cell(total('guest'))}** | **${cell(total('account'))}** | **${cell(total('docxGuest'))}** | **${cell(total('redactorOnEcho'))}** |`);
  lines.push('');

  lines.push('## Content kept for the review');
  lines.push('');
  lines.push('The value, then what the text starting at that value looked like after masking.');
  lines.push('');
  lines.push('| Resume | Guest kept | Logged in kept | Lost as a guest | Lost when logged in |');
  lines.push('|---|---|---|---|---|');
  for (const r of results) {
    const count = (s) => `${r.keep.filter((k) => k[s] === 'kept').length}/${r.keep.filter((k) => k[s] !== 'absent').length}`;
    const lost = (s) => r.keep.filter((k) => k[s] === 'lost').map((k) => `\`${k.value}\` → \`${k[`${s}Rewrite`]}\``).join('<br>') || '—';
    lines.push(`| ${r.id} | ${count('guest')} | ${count('account')} | ${lost('guest')} | ${lost('account')} |`);
  }
  lines.push('');

  lines.push('## Per resume');
  for (const r of results) {
    lines.push('');
    lines.push(`### ${r.id} — ${r.career}, ${r.country}`);
    lines.push('');
    lines.push(`Layout \`${r.layout}\` · PDF extracted as ${r.pdfLinesExtracted} line(s) · header name guessed from PDF: ${r.headerNamePdf ? `\`${r.headerNamePdf}\`` : '**none**'} · from DOCX: ${r.headerNameDocx ? `\`${r.headerNameDocx}\`` : '**none**'}`);
    lines.push('');
    lines.push('| Category | Value | PDF guest | PDF logged in | DOCX guest | Redactor on echo |');
    lines.push('|---|---|---|---|---|---|');
    for (const item of r.items) {
      const show = (res) => `${mark[res.status]}${res.status === 'partial' ? ` left: ${res.left.join(', ')}` : ''}`;
      lines.push(`| ${CATEGORY_LABELS[item.cat]}${item.note ? ` (${item.note})` : ''} | \`${item.value}\` | ${show(item.guest)} | ${show(item.account)} | ${show(item.docxGuest)} | ${show(item.redactorOnEcho)} |`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

async function main() {
  await fs.mkdir(OUTBOUND_DIR, { recursive: true });
  const docxDir = await fs.mkdtemp(path.join(os.tmpdir(), 'pii-audit-'));

  const results = [];
  for (const entry of SET) {
    const { outbound, ...result } = await auditEntry(entry, docxDir);
    await fs.writeFile(path.join(OUTBOUND_DIR, `${entry.id}.txt`), outbound);
    results.push(result);
    console.log(`audited ${entry.id}`);
  }

  await fs.writeFile(path.join(CORPUS_DIR, `results${SUFFIX}.json`), `${JSON.stringify(results, null, 2)}\n`);
  await fs.writeFile(path.join(CORPUS_DIR, `RESULTS${SUFFIX}.md`), renderMarkdown(results));
  await fs.rm(docxDir, { recursive: true, force: true });

  const byCat = tally(results);
  console.log('\ncategory            guest        account      docx-guest   redactor-echo');
  for (const [cat, t] of Object.entries(byCat)) {
    console.log(`${cat.padEnd(18)}  ${SCENARIOS.map((s) => cell(t[s]).padEnd(12)).join(' ')}`);
  }
  const unexplained = results.reduce((n, r) => n + r.unexplained.guest.length + r.unexplained.account.length, 0);
  console.log(`\nremoved but not personal (over-masking): ${unexplained}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
