/**
 * The team's own sample CVs (docs/database, docs/samples/mock_interview),
 * scored by the same audit as the corpus. These were written before the mask
 * was reworked and never tuned against, and they caught four bugs the corpus
 * did not (see "Team sample CVs" in docs/qa/PII_MASK_AUDIT.md).
 *
 * Same shape as corpus.js, with `file` (repo-relative) in place of a `cv` to
 * build. The BD_Resume_Test files are left out: their personal details are
 * already template placeholders, so there is nothing to score.
 */

export const TEAM_SAMPLES = [
  {
    id: 'team-fahmida-akter',
    file: 'docs/database/bangladesh_resume_fahmida_akter.pdf',
    career: 'Financial Analyst',
    sector: 'Banking',
    country: 'Bangladesh',
    layout: 'two-page with repeated header',
    account: { fullName: 'Fahmida Akter', email: 'fahmida.akter@gmail.com', phone: '+880-1812-345678' },
    pii: [
      { cat: 'name', value: 'Fahmida Akter' },
      { cat: 'email', value: 'fahmida.akter@gmail.com' },
      { cat: 'phone', value: '+880-1812-345678' },
      { cat: 'url', value: 'linkedin.com/in/fahmida-akter' },
      { cat: 'address', value: 'Flat 4B, House 22, Mirpur Road, Dhanmondi, Dhaka-1207' },
      { cat: 'address', value: 'Kaliganj' },
      { cat: 'address', value: 'Gazipur-1750' },
      { cat: 'dob', value: '8 November 2000' },
      { cat: 'gov-id', value: '198001234567891' },
      { cat: 'family', value: 'Abul Hossain' },
      { cat: 'family', value: 'Rahela Begum' },
      { cat: 'sensitive', value: 'Gender Female' },
      { cat: 'sensitive', value: 'Religion Islam' },
      { cat: 'sensitive', value: 'Marital Status Single' },
      { cat: 'sensitive', value: 'Blood Group O+' },
      { cat: 'referee', value: 'Mosharraf Hossain' },
      { cat: 'referee', value: '+880-1755-112233' },
      { cat: 'referee', value: 'mosharraf@du.ac.bd' },
      { cat: 'referee', value: 'Asif Rahman' },
      { cat: 'referee', value: '+880-1833-556677' },
      { cat: 'referee', value: 'asif.rahman@primebank.com.bd' },
    ],
    keep: ['Prime Bank Limited', 'IDLC Finance Limited', 'University of Dhaka', 'Viqarunnissa Noon College',
      'students in Mirpur secondary schools', 'Professor, Dept. of Finance', 'Senior Vice President, SME Banking',
      'BRPD Circular No. 14'],
  },
  {
    id: 'team-rafiqul-islam',
    file: 'docs/database/bangladesh_resume_rafiqul_islam.pdf',
    career: 'Software Engineer',
    sector: 'Technology',
    country: 'Bangladesh',
    layout: 'two-column, icon contacts, side-by-side referees',
    account: { fullName: 'Md. Rafiqul Islam', email: 'rafiqul.islam@gmail.com', phone: '+880-1711-234567' },
    pii: [
      { cat: 'name', value: 'Rafiqul Islam' },
      { cat: 'email', value: 'rafiqul.islam@gmail.com' },
      { cat: 'phone', value: '+880-1711-234567' },
      { cat: 'address', value: 'House 12, Road 5, Dhanmondi, Dhaka-1205' },
      { cat: 'url', value: 'linkedin.com/in/md-rafiqul-islam' },
      { cat: 'url', value: 'github.com/rafiqul-islam' },
      { cat: 'dob', value: '15 March 2001' },
      { cat: 'gov-id', value: '19801234567890' },
      { cat: 'family', value: 'Abdul Karim' },
      { cat: 'family', value: 'Fatema Begum' },
      { cat: 'address', value: 'Baraigram' },
      { cat: 'address', value: 'Natore-6420' },
      { cat: 'sensitive', value: 'Gender Male' },
      { cat: 'sensitive', value: 'Religion Islam' },
      { cat: 'sensitive', value: 'Marital Status Single' },
      { cat: 'sensitive', value: 'Blood Group B+' },
      // Printed side by side, so both names extract onto one line.
      { cat: 'referee', value: 'A.K.M. Ashikur Rahman' },
      { cat: 'referee', value: 'Tanvir Hossain' },
      { cat: 'referee', value: '+880-1755-000123' },
      { cat: 'referee', value: 'ashikur@cse.buet.ac.bd' },
      { cat: 'referee', value: '+880-1833-456789' },
      { cat: 'referee', value: 'tanvir.hossain@bracit.com.bd' },
    ],
    keep: ['B.Sc. in Computer Science & Engineering 2018 – 2022', 'Bangladesh University of Engineering and Technology',
      'BRAC IT Services Ltd.', 'Assoc. Professor, Dept. of CSE, BUET', 'Notre Dame College', 'Dhaka Collegiate School'],
  },
  {
    id: 'team-rafiqul-islam-v2',
    file: 'docs/database/bangladesh_resume_rafiqul_islam_v2.pdf',
    career: 'Software Engineer',
    sector: 'Technology',
    country: 'Bangladesh',
    layout: 'labelled contacts, references on request',
    account: { fullName: 'Md. Rafiqul Islam', email: 'rafiqul.islam@gmail.com', phone: '+880-1711-234567' },
    pii: [
      { cat: 'name', value: 'Rafiqul Islam' },
      { cat: 'email', value: 'rafiqul.islam@gmail.com' },
      { cat: 'phone', value: '+880-1711-234567' },
      { cat: 'address', value: 'House 12, Road 5, Dhanmondi, Dhaka-1205' },
      { cat: 'url', value: 'linkedin.com/in/md-rafiqul-islam' },
      { cat: 'url', value: 'github.com/rafiqul-islam' },
      { cat: 'family', value: 'Abdul Karim' },
      { cat: 'family', value: 'Fatema Begum' },
      { cat: 'address', value: 'Baraigram' },
      { cat: 'address', value: 'Natore-6420' },
    ],
    keep: ['B.Sc. in Computer Science & Engineering 2018 – 2022', 'References available upon request',
      'BRAC IT Services Ltd.', 'Nationality Bangladeshi'],
  },
  {
    id: 'team-sakib-hasan',
    file: 'docs/samples/mock_interview/cv_sakib_hasan_cse_fresher.pdf',
    career: 'Junior Software Engineer (fresher)',
    sector: 'Technology',
    country: 'Bangladesh',
    layout: 'single column, spaced colons',
    account: { fullName: 'Md. Sakib Hasan', email: 'sakib.hasan.cse@gmail.com', phone: '01715-882341' },
    pii: [
      { cat: 'name', value: 'Sakib Hasan' },
      { cat: 'address', value: 'House 12, Road 7, Block C, Mirpur-11, Dhaka-1216' },
      { cat: 'phone', value: '01715-882341' },
      { cat: 'email', value: 'sakib.hasan.cse@gmail.com' },
      { cat: 'url', value: 'github.com/sakibhasan-dev' },
      { cat: 'dob', value: '15 March 2002' },
      { cat: 'family', value: 'Abul Hasan' },
      { cat: 'family', value: 'Rokeya Begum' },
      { cat: 'sensitive', value: 'Religion Islam' },
      { cat: 'sensitive', value: 'Marital Status Single' },
      { cat: 'gov-id', value: '5512345678901' },
      { cat: 'referee', value: 'Farhana Rahman' },
      { cat: 'referee', value: 'farhana.rahman@bracu.ac.bd' },
    ],
    keep: ['Web : HTML, CSS, React, Node.js, Express', 'Assistant Professor, Department of CSE', 'BRAC University'],
  },
  {
    id: 'team-sharmin-sultana',
    file: 'docs/samples/mock_interview/cv_sharmin_sultana_hr.pdf',
    career: 'HR Executive',
    sector: 'Human resources',
    country: 'Bangladesh',
    layout: 'single column, signature block',
    account: { fullName: 'Sharmin Sultana', email: 'sharmin_sultana95@gmail.com', phone: '01856-712934' },
    pii: [
      { cat: 'name', value: 'Sharmin Sultana' },
      { cat: 'address', value: 'Flat 2A, 44 North Badda, Dhaka-1212' },
      { cat: 'phone', value: '01856-712934' },
      { cat: 'email', value: 'sharmin_sultana95@gmail.com' },
      { cat: 'family', value: 'Shahabuddin Mia' },
      { cat: 'family', value: 'Ranu Begum' },
      { cat: 'dob', value: '12 October, 1997' },
      { cat: 'sensitive', value: 'Gender Female' },
      { cat: 'sensitive', value: 'Religion Islam' },
      { cat: 'sensitive', value: 'Blood Group AB (Positive)' },
      { cat: 'sensitive', value: 'Marital Status Unmarried' },
      { cat: 'address', value: 'Baraigram' },
      { cat: 'address', value: 'Natore-6460' },
    ],
    keep: ['HR or admin department', 'Nationality : Bangladeshi', 'DECLARATION'],
  },
  {
    id: 'team-nusrat-jahan',
    file: 'docs/samples/mock_interview/cv_nusrat_jahan_mba_finance.docx',
    career: 'Management Trainee (MBA Finance)',
    sector: 'Banking',
    country: 'Bangladesh',
    layout: 'DOCX, aligned colons',
    account: { fullName: 'Nusrat Jahan', email: 'nusrat.jahan.fin@gmail.com', phone: '01911-347820' },
    pii: [
      { cat: 'name', value: 'Nusrat Jahan' },
      { cat: 'address', value: 'Flat 5B, House 18, Road 3, Dhanmondi, Dhaka-1205' },
      { cat: 'phone', value: '01911-347820' },
      { cat: 'email', value: 'nusrat.jahan.fin@gmail.com' },
      { cat: 'dob', value: '22 August 1999' },
      { cat: 'family', value: 'Jahangir Alam' },
      { cat: 'family', value: 'Shirin Akter' },
      { cat: 'sensitive', value: 'Religion Islam' },
      { cat: 'sensitive', value: 'Marital Status Single' },
      { cat: 'sensitive', value: 'Blood Group B+' },
      { cat: 'gov-id', value: '1998123456789' },
      { cat: 'referee', value: 'Rezaul Karim' },
      { cat: 'referee', value: '01712-000111' },
    ],
    keep: ['Department of Finance, University of Dhaka', 'MBA (Finance)', 'Nationality : Bangladeshi'],
  },
];
