-- Bangla translations for career-path titles/skills/progression and alumni
-- names/institutions/roles. Fills the columns added in
-- add_full_bilingual_content.sql.
--
-- Skills keep software/tool/platform/certification product names in Latin
-- script (Excel, PostgreSQL, React, AWS, AutoCAD, CFA, GMP...) -- see that
-- migration's header for why.
--
-- Idempotent with respect to the English columns; safe to run more than once.

BEGIN;

-- ── career_paths ────────────────────────────────────────────────────────
UPDATE career_paths SET title_bn = 'আর্থিক বিশ্লেষক', skills_bn = '["Excel", "আর্থিক মডেলিং", "হিসাববিজ্ঞান", "ডেটা বিশ্লেষণ", "রিপোর্ট লেখা"]'::jsonb, progression_bn = '[{"label": "জুনিয়র বিশ্লেষক", "time": "0–1 yr"}, {"label": "আর্থিক বিশ্লেষক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র বিশ্লেষক", "time": "3–5 yrs"}, {"label": "ফাইন্যান্স ম্যানেজার", "time": "5–8 yrs"}, {"label": "সিএফও", "time": "8+ yrs"}]'::jsonb WHERE id = 1;
UPDATE career_paths SET title_bn = 'ব্যাংক সম্পর্ক কর্মকর্তা', skills_bn = '["গ্রাহকসেবা", "ঋণ প্রক্রিয়াকরণ", "CRM সফটওয়্যার", "যোগাযোগ", "বিক্রয়"]'::jsonb, progression_bn = '[{"label": "ট্রেইনি অফিসার", "time": "0–1 yr"}, {"label": "রিলেশনশিপ অফিসার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র কর্মকর্তা", "time": "3–5 yrs"}, {"label": "শাখা ব্যবস্থাপক", "time": "5–8 yrs"}, {"label": "রিজিওনাল ম্যানেজার", "time": "8+ yrs"}]'::jsonb WHERE id = 2;
UPDATE career_paths SET title_bn = 'নিরীক্ষা সহযোগী', skills_bn = '["নিরীক্ষা মানদণ্ড", "খুঁটিনাটি বিষয়ে মনোযোগ", "হিসাবরক্ষণ সফটওয়্যার", "বিশ্লেষণাত্মক চিন্তাভাবনা", "রিপোর্ট লেখা"]'::jsonb, progression_bn = '[{"label": "নিরীক্ষা ট্রেইনি", "time": "0–1 yr"}, {"label": "নিরীক্ষা সহযোগী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র নিরীক্ষক", "time": "3–5 yrs"}, {"label": "নিরীক্ষা ব্যবস্থাপক", "time": "5–8 yrs"}, {"label": "পার্টনার", "time": "8+ yrs"}]'::jsonb WHERE id = 3;
UPDATE career_paths SET title_bn = 'কর পরামর্শক', skills_bn = '["কর আইন", "নিয়মপালন", "ক্লায়েন্ট ব্যবস্থাপনা", "বিশ্লেষণাত্মক দক্ষতা", "যোগাযোগ"]'::jsonb, progression_bn = '[{"label": "কর ট্রেইনি", "time": "0–1 yr"}, {"label": "কর পরামর্শক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র পরামর্শক", "time": "3–5 yrs"}, {"label": "কর ব্যবস্থাপক", "time": "5–8 yrs"}, {"label": "কর পার্টনার", "time": "8+ yrs"}]'::jsonb WHERE id = 4;
UPDATE career_paths SET title_bn = 'বিনিয়োগ বিশ্লেষক', skills_bn = '["আর্থিক গবেষণা", "শেয়ারবাজার", "ভ্যালুয়েশন", "Bloomberg Terminal", "ঝুঁকি মূল্যায়ন"]'::jsonb, progression_bn = '[{"label": "গবেষণা সহকারী", "time": "0–1 yr"}, {"label": "বিনিয়োগ বিশ্লেষক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র বিশ্লেষক", "time": "3–5 yrs"}, {"label": "পোর্টফোলিও ম্যানেজার", "time": "5–8 yrs"}, {"label": "বিনিয়োগ ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 5;
UPDATE career_paths SET title_bn = 'ঋণ ঝুঁকি কর্মকর্তা', skills_bn = '["ঝুঁকি মূল্যায়ন", "ক্রেডিট স্কোরিং", "আর্থিক বিশ্লেষণ", "নিয়ন্ত্রক জ্ঞান", "সিদ্ধান্ত গ্রহণ"]'::jsonb, progression_bn = '[{"label": "ক্রেডিট ট্রেইনি", "time": "0–1 yr"}, {"label": "ক্রেডিট কর্মকর্তা", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ক্রেডিট কর্মকর্তা", "time": "3–5 yrs"}, {"label": "ক্রেডিট ব্যবস্থাপক", "time": "5–8 yrs"}, {"label": "চিফ রিস্ক অফিসার", "time": "8+ yrs"}]'::jsonb WHERE id = 6;
UPDATE career_paths SET title_bn = 'হিসাবরক্ষণ নির্বাহী', skills_bn = '["হিসাবরক্ষণ", "Tally/QuickBooks", "চালান প্রক্রিয়াকরণ", "হিসাব মিলকরণ", "আর্থিক প্রতিবেদন"]'::jsonb, progression_bn = '[{"label": "হিসাব সহকারী", "time": "0–1 yr"}, {"label": "হিসাবরক্ষণ নির্বাহী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র হিসাবরক্ষক", "time": "3–5 yrs"}, {"label": "ফাইন্যান্স কন্ট্রোলার", "time": "5–8 yrs"}, {"label": "ফাইন্যান্স ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 7;
UPDATE career_paths SET title_bn = 'ট্রেজারি বিশ্লেষক', skills_bn = '["নগদ ব্যবস্থাপনা", "ফরেক্স", "ব্যাংকিং", "Excel", "আর্থিক বাজার"]'::jsonb, progression_bn = '[{"label": "ট্রেজারি সহকারী", "time": "0–1 yr"}, {"label": "ট্রেজারি বিশ্লেষক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ট্রেজারি বিশ্লেষক", "time": "3–5 yrs"}, {"label": "ট্রেজারি ব্যবস্থাপক", "time": "5–8 yrs"}, {"label": "গ্রুপ ট্রেজারার", "time": "8+ yrs"}]'::jsonb WHERE id = 8;
UPDATE career_paths SET title_bn = 'ক্ষুদ্রঋণ কর্মকর্তা', skills_bn = '["মাঠকর্ম", "ক্লায়েন্ট মূল্যায়ন", "ঋণ আদায়", "সম্প্রদায় সম্পর্ক", "ডকুমেন্টেশন"]'::jsonb, progression_bn = '[{"label": "মাঠ কর্মকর্তা", "time": "0–1 yr"}, {"label": "ক্ষুদ্রঋণ কর্মকর্তা", "time": "1–3 yrs", "current": true}, {"label": "শাখা ব্যবস্থাপক", "time": "3–5 yrs"}, {"label": "এরিয়া ম্যানেজার", "time": "5–8 yrs"}, {"label": "রিজিওনাল ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 9;
UPDATE career_paths SET title_bn = 'বিমা আন্ডাররাইটার', skills_bn = '["ঝুঁকি মূল্যায়ন", "বিমা পলিসি", "ডেটা বিশ্লেষণ", "চিকিৎসা পরিভাষা", "আইনি জ্ঞান"]'::jsonb, progression_bn = '[{"label": "আন্ডাররাইটিং ট্রেইনি", "time": "0–1 yr"}, {"label": "আন্ডাররাইটার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র আন্ডাররাইটার", "time": "3–5 yrs"}, {"label": "আন্ডাররাইটিং ম্যানেজার", "time": "5–8 yrs"}, {"label": "চিফ আন্ডাররাইটার", "time": "8+ yrs"}]'::jsonb WHERE id = 10;
UPDATE career_paths SET title_bn = 'সফটওয়্যার প্রকৌশলী', skills_bn = '["JavaScript", "React", "Node.js", "PostgreSQL", "Git", "REST APIs"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ডেভেলপার", "time": "0–1 yr"}, {"label": "সফটওয়্যার প্রকৌশলী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "3–6 yrs"}, {"label": "টেক লিড", "time": "6–9 yrs"}, {"label": "সিটিও", "time": "9+ yrs"}]'::jsonb WHERE id = 11;
UPDATE career_paths SET title_bn = 'ফ্রন্টএন্ড ডেভেলপার', skills_bn = '["React", "Vue.js", "HTML/CSS", "JavaScript", "রেসপন্সিভ ডিজাইন", "Figma"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ফ্রন্টএন্ড", "time": "0–1 yr"}, {"label": "ফ্রন্টএন্ড ডেভেলপার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ফ্রন্টএন্ড", "time": "3–5 yrs"}, {"label": "ফ্রন্টএন্ড লিড", "time": "5–8 yrs"}, {"label": "ইউআই/ইউএক্স ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 12;
UPDATE career_paths SET title_bn = 'ব্যাকএন্ড ডেভেলপার', skills_bn = '["Python/Django", "Node.js", "SQL", "API ডিজাইন", "সার্ভার ব্যবস্থাপনা", "নিরাপত্তা"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ব্যাকএন্ড", "time": "0–1 yr"}, {"label": "ব্যাকএন্ড ডেভেলপার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ব্যাকএন্ড", "time": "3–5 yrs"}, {"label": "ব্যাকএন্ড আর্কিটেক্ট", "time": "5–8 yrs"}, {"label": "ইঞ্জিনিয়ারিং ব্যবস্থাপক", "time": "8+ yrs"}]'::jsonb WHERE id = 13;
UPDATE career_paths SET title_bn = 'ডেভঅপস প্রকৌশলী', skills_bn = '["AWS/GCP", "Docker", "Kubernetes", "CI/CD", "Linux", "মনিটরিং টুলস"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ডেভঅপস", "time": "0–1 yr"}, {"label": "ডেভঅপস প্রকৌশলী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ডেভঅপস", "time": "3–5 yrs"}, {"label": "প্ল্যাটফর্ম আর্কিটেক্ট", "time": "5–8 yrs"}, {"label": "ইনফ্রাস্ট্রাকচার প্রধান", "time": "8+ yrs"}]'::jsonb WHERE id = 14;
UPDATE career_paths SET title_bn = 'ডেটা বিশ্লেষক', skills_bn = '["SQL", "Python", "Excel", "Tableau", "পরিসংখ্যানগত বিশ্লেষণ", "ডেটা ভিজ্যুয়ালাইজেশন"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ডেটা বিশ্লেষক", "time": "0–1 yr"}, {"label": "ডেটা বিশ্লেষক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ডেটা বিশ্লেষক", "time": "3–5 yrs"}, {"label": "ডেটা সায়েন্টিস্ট", "time": "5–8 yrs"}, {"label": "ডেটা প্রধান", "time": "8+ yrs"}]'::jsonb WHERE id = 15;
UPDATE career_paths SET title_bn = 'কিউএ প্রকৌশলী', skills_bn = '["ম্যানুয়াল টেস্টিং", "অটোমেশন", "Selenium", "বাগ ট্র্যাকিং", "টেস্ট কেস", "খুঁটিনাটি বিষয়ে মনোযোগ"]'::jsonb, progression_bn = '[{"label": "জুনিয়র কিউএ", "time": "0–1 yr"}, {"label": "কিউএ প্রকৌশলী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র কিউএ", "time": "3–5 yrs"}, {"label": "কিউএ লিড", "time": "5–8 yrs"}, {"label": "কিউএ ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 16;
UPDATE career_paths SET title_bn = 'ডেটাবেজ অ্যাডমিনিস্ট্রেটর', skills_bn = '["PostgreSQL", "MySQL", "MongoDB", "ব্যাকআপ/রিকভারি", "পারফরম্যান্স টিউনিং", "নিরাপত্তা"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ডিবিএ", "time": "0–1 yr"}, {"label": "ডিবিএ", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ডিবিএ", "time": "3–5 yrs"}, {"label": "ডেটাবেজ আর্কিটেক্ট", "time": "5–8 yrs"}, {"label": "ডেটা প্ল্যাটফর্ম লিড", "time": "8+ yrs"}]'::jsonb WHERE id = 17;
UPDATE career_paths SET title_bn = 'সাইবার নিরাপত্তা বিশ্লেষক', skills_bn = '["নেটওয়ার্ক নিরাপত্তা", "দুর্বলতা মূল্যায়ন", "SIEM টুলস", "ঝুঁকি ব্যবস্থাপনা", "এথিক্যাল হ্যাকিং"]'::jsonb, progression_bn = '[{"label": "সিকিউরিটি ট্রেইনি", "time": "0–1 yr"}, {"label": "সিকিউরিটি বিশ্লেষক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র সিকিউরিটি বিশ্লেষক", "time": "3–5 yrs"}, {"label": "সিকিউরিটি ম্যানেজার", "time": "5–8 yrs"}, {"label": "সিআইএসও", "time": "8+ yrs"}]'::jsonb WHERE id = 18;
UPDATE career_paths SET title_bn = 'আইটি সাপোর্ট স্পেশালিস্ট', skills_bn = '["হার্ডওয়্যার ট্রাবলশুটিং", "নেটওয়ার্কিং", "Windows/Linux", "গ্রাহকসেবা", "টিকেটিং সিস্টেম"]'::jsonb, progression_bn = '[{"label": "আইটি সাপোর্ট লেভেল ১", "time": "0–1 yr"}, {"label": "আইটি সাপোর্ট স্পেশালিস্ট", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র আইটি সাপোর্ট", "time": "3–5 yrs"}, {"label": "আইটি ম্যানেজার", "time": "5–8 yrs"}, {"label": "আইটি ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 19;
UPDATE career_paths SET title_bn = 'মোবাইল অ্যাপ ডেভেলপার', skills_bn = '["Flutter", "React Native", "Android", "iOS", "অ্যাপ স্টোর ডিপ্লয়মেন্ট", "REST APIs"]'::jsonb, progression_bn = '[{"label": "জুনিয়র মোবাইল ডেভেলপার", "time": "0–1 yr"}, {"label": "মোবাইল ডেভেলপার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র মোবাইল ডেভেলপার", "time": "3–5 yrs"}, {"label": "মোবাইল টেক লিড", "time": "5–8 yrs"}, {"label": "মোবাইল প্রধান", "time": "8+ yrs"}]'::jsonb WHERE id = 20;
UPDATE career_paths SET title_bn = 'সিভিল প্রকৌশলী', skills_bn = '["AutoCAD", "কাঠামোগত বিশ্লেষণ", "প্রকল্প ব্যবস্থাপনা", "সাইট তদারকি", "ব্যয় নিরূপণ"]'::jsonb, progression_bn = '[{"label": "সাইট ইঞ্জিনিয়ার", "time": "0–2 yrs"}, {"label": "সিভিল প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "প্রকল্প ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "চিফ ইঞ্জিনিয়ার", "time": "10+ yrs"}]'::jsonb WHERE id = 21;
UPDATE career_paths SET title_bn = 'ইলেকট্রিক্যাল প্রকৌশলী', skills_bn = '["সার্কিট ডিজাইন", "পাওয়ার সিস্টেম", "AutoCAD Electrical", "PLC প্রোগ্রামিং", "নিরাপত্তা মানদণ্ড"]'::jsonb, progression_bn = '[{"label": "জুনিয়র প্রকৌশলী", "time": "0–2 yrs"}, {"label": "ইলেকট্রিক্যাল প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "প্রকল্প ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "চিফ ইঞ্জিনিয়ার", "time": "10+ yrs"}]'::jsonb WHERE id = 22;
UPDATE career_paths SET title_bn = 'মেকানিক্যাল প্রকৌশলী', skills_bn = '["SolidWorks", "তাপগতিবিদ্যা", "উৎপাদন প্রক্রিয়া", "রক্ষণাবেক্ষণ", "CAD"]'::jsonb, progression_bn = '[{"label": "জুনিয়র প্রকৌশলী", "time": "0–2 yrs"}, {"label": "মেকানিক্যাল প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "প্ল্যান্ট ম্যানেজার", "time": "7–10 yrs"}, {"label": "অপারেশনস ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 23;
UPDATE career_paths SET title_bn = 'কেমিক্যাল প্রকৌশলী', skills_bn = '["প্রক্রিয়া ডিজাইন", "নিরাপত্তা প্রোটোকল", "মান নিয়ন্ত্রণ", "তাপগতিবিদ্যা", "ল্যাব সরঞ্জাম"]'::jsonb, progression_bn = '[{"label": "প্রসেস ট্রেইনি", "time": "0–2 yrs"}, {"label": "কেমিক্যাল প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "প্রোডাকশন ম্যানেজার", "time": "7–10 yrs"}, {"label": "প্ল্যান্ট ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 24;
UPDATE career_paths SET title_bn = 'টেক্সটাইল প্রকৌশলী', skills_bn = '["কাপড় উৎপাদন", "মান নিয়ন্ত্রণ", "রং করার প্রক্রিয়া", "সাপ্লাই চেইন", "কারখানা ব্যবস্থাপনা"]'::jsonb, progression_bn = '[{"label": "প্রোডাকশন ট্রেইনি", "time": "0–2 yrs"}, {"label": "টেক্সটাইল প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "প্রোডাকশন ম্যানেজার", "time": "7–10 yrs"}, {"label": "ফ্যাক্টরি ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 25;
UPDATE career_paths SET title_bn = 'ইন্ডাস্ট্রিয়াল প্রকৌশলী', skills_bn = '["প্রক্রিয়া অপ্টিমাইজেশন", "Six Sigma", "সাপ্লাই চেইন", "ডেটা বিশ্লেষণ", "লিন ম্যানুফ্যাকচারিং"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ইন্ডাস্ট্রিয়াল প্রকৌশলী", "time": "0–2 yrs"}, {"label": "ইন্ডাস্ট্রিয়াল প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র ইন্ডাস্ট্রিয়াল প্রকৌশলী", "time": "4–7 yrs"}, {"label": "অপারেশনস ম্যানেজার", "time": "7–10 yrs"}, {"label": "সিওও", "time": "10+ yrs"}]'::jsonb WHERE id = 26;
UPDATE career_paths SET title_bn = 'পরিবেশ প্রকৌশলী', skills_bn = '["পরিবেশগত প্রভাব মূল্যায়ন", "বর্জ্য ব্যবস্থাপনা", "পানি শোধন", "নিয়মপালন", "মাঠকর্ম"]'::jsonb, progression_bn = '[{"label": "জুনিয়র প্রকৌশলী", "time": "0–2 yrs"}, {"label": "পরিবেশ প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "প্রকল্প ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "ইএইচএস পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 27;
UPDATE career_paths SET title_bn = 'টেলিযোগাযোগ প্রকৌশলী', skills_bn = '["নেটওয়ার্ক ডিজাইন", "RF ইঞ্জিনিয়ারিং", "ফাইবার অপটিক্স", "সিগন্যাল প্রসেসিং", "ট্রাবলশুটিং"]'::jsonb, progression_bn = '[{"label": "নেটওয়ার্ক ট্রেইনি", "time": "0–2 yrs"}, {"label": "টেলিকম প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "নেটওয়ার্ক ম্যানেজার", "time": "7–10 yrs"}, {"label": "সিটিও", "time": "10+ yrs"}]'::jsonb WHERE id = 28;
UPDATE career_paths SET title_bn = 'অটোমোবাইল প্রকৌশলী', skills_bn = '["যানবাহন সিস্টেম", "ডায়াগনস্টিকস", "CAD", "যান্ত্রিক মেরামত", "মান নিশ্চয়তা"]'::jsonb, progression_bn = '[{"label": "সার্ভিস ইঞ্জিনিয়ার", "time": "0–2 yrs"}, {"label": "অটোমোবাইল প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "সার্ভিস ম্যানেজার", "time": "7–10 yrs"}, {"label": "অপারেশনস ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 29;
UPDATE career_paths SET title_bn = 'মেরিন প্রকৌশলী', skills_bn = '["জাহাজ সিস্টেম", "সামুদ্রিক নিরাপত্তা", "রক্ষণাবেক্ষণ", "নেভিগেশন সিস্টেম", "নিয়ন্ত্রক সম্মতি"]'::jsonb, progression_bn = '[{"label": "জুনিয়র প্রকৌশলী", "time": "0–2 yrs"}, {"label": "মেরিন প্রকৌশলী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র প্রকৌশলী", "time": "4–7 yrs"}, {"label": "চিফ ইঞ্জিনিয়ার", "time": "7–10 yrs"}, {"label": "ফ্লিট ম্যানেজার", "time": "10+ yrs"}]'::jsonb WHERE id = 30;
UPDATE career_paths SET title_bn = 'মার্কেটিং নির্বাহী', skills_bn = '["ডিজিটাল মার্কেটিং", "সোশ্যাল মিডিয়া", "বাজার গবেষণা", "ক্যাম্পেইন ব্যবস্থাপনা", "অ্যানালিটিক্স"]'::jsonb, progression_bn = '[{"label": "মার্কেটিং ট্রেইনি", "time": "0–1 yr"}, {"label": "মার্কেটিং নির্বাহী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র নির্বাহী", "time": "3–5 yrs"}, {"label": "ব্র্যান্ড ম্যানেজার", "time": "5–8 yrs"}, {"label": "মার্কেটিং ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 31;
UPDATE career_paths SET title_bn = 'এইচআর নির্বাহী', skills_bn = '["নিয়োগ", "বেতন ব্যবস্থাপনা", "শ্রম আইন", "যোগাযোগ", "কর্মী সম্পৃক্ততা"]'::jsonb, progression_bn = '[{"label": "এইচআর ট্রেইনি", "time": "0–1 yr"}, {"label": "এইচআর নির্বাহী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র এইচআর নির্বাহী", "time": "3–5 yrs"}, {"label": "এইচআর ম্যানেজার", "time": "5–8 yrs"}, {"label": "এইচআর ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 32;
UPDATE career_paths SET title_bn = 'ব্যবসা উন্নয়ন কর্মকর্তা', skills_bn = '["বিক্রয়", "দরকষাকষি", "ক্লায়েন্ট সম্পর্ক", "বাজার গবেষণা", "যোগাযোগ"]'::jsonb, progression_bn = '[{"label": "সেলস ট্রেইনি", "time": "0–1 yr"}, {"label": "বিডিও", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র বিডিও", "time": "3–5 yrs"}, {"label": "সেলস ম্যানেজার", "time": "5–8 yrs"}, {"label": "সেলস ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 33;
UPDATE career_paths SET title_bn = 'সাপ্লাই চেইন কর্মকর্তা', skills_bn = '["ক্রয়", "লজিস্টিকস", "ইনভেন্টরি ব্যবস্থাপনা", "ভেন্ডর সম্পর্ক", "ERP সিস্টেম"]'::jsonb, progression_bn = '[{"label": "সাপ্লাই চেইন ট্রেইনি", "time": "0–1 yr"}, {"label": "সাপ্লাই চেইন কর্মকর্তা", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র কর্মকর্তা", "time": "3–5 yrs"}, {"label": "সাপ্লাই চেইন ম্যানেজার", "time": "5–8 yrs"}, {"label": "লজিস্টিকস ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 34;
UPDATE career_paths SET title_bn = 'অপারেশনস নির্বাহী', skills_bn = '["প্রক্রিয়া উন্নয়ন", "দল ব্যবস্থাপনা", "সমস্যা সমাধান", "রিপোর্টিং", "সমন্বয়"]'::jsonb, progression_bn = '[{"label": "অপারেশনস ট্রেইনি", "time": "0–1 yr"}, {"label": "অপারেশনস নির্বাহী", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র নির্বাহী", "time": "3–5 yrs"}, {"label": "অপারেশনস ম্যানেজার", "time": "5–8 yrs"}, {"label": "সিওও", "time": "8+ yrs"}]'::jsonb WHERE id = 35;
UPDATE career_paths SET title_bn = 'রপ্তানি-আমদানি কর্মকর্তা', skills_bn = '["কাস্টমস নথিপত্র", "LC প্রক্রিয়া", "আন্তর্জাতিক বাণিজ্য আইন", "ফ্রেইট ফরওয়ার্ডিং", "দরকষাকষি"]'::jsonb, progression_bn = '[{"label": "ট্রেড ট্রেইনি", "time": "0–1 yr"}, {"label": "রপ্তানি-আমদানি কর্মকর্তা", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র কর্মকর্তা", "time": "3–5 yrs"}, {"label": "ট্রেড ম্যানেজার", "time": "5–8 yrs"}, {"label": "ট্রেড ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 36;
UPDATE career_paths SET title_bn = 'কাস্টমার সাকসেস ম্যানেজার', skills_bn = '["গ্রাহকসেবা", "সমস্যা সমাধান", "যোগাযোগ", "CRM সফটওয়্যার", "ধরে রাখার কৌশল"]'::jsonb, progression_bn = '[{"label": "কাস্টমার সাপোর্ট", "time": "0–1 yr"}, {"label": "সিএসএম", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র সিএসএম", "time": "3–5 yrs"}, {"label": "কাস্টমার সাকসেস লিড", "time": "5–8 yrs"}, {"label": "কাস্টমার সাকসেস প্রধান", "time": "8+ yrs"}]'::jsonb WHERE id = 37;
UPDATE career_paths SET title_bn = 'প্রকল্প সমন্বয়কারী', skills_bn = '["প্রকল্প পরিকল্পনা", "MS Project", "যোগাযোগ", "ঝুঁকি ব্যবস্থাপনা", "বাজেট পর্যবেক্ষণ"]'::jsonb, progression_bn = '[{"label": "প্রকল্প সহকারী", "time": "0–1 yr"}, {"label": "প্রকল্প সমন্বয়কারী", "time": "1–3 yrs", "current": true}, {"label": "প্রকল্প ব্যবস্থাপক", "time": "3–5 yrs"}, {"label": "সিনিয়র পিএম", "time": "5–8 yrs"}, {"label": "প্রোগ্রাম ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 38;
UPDATE career_paths SET title_bn = 'ই-কমার্স ম্যানেজার', skills_bn = '["ই-কমার্স প্ল্যাটফর্ম", "ডিজিটাল মার্কেটিং", "ইনভেন্টরি ব্যবস্থাপনা", "গ্রাহক অভিজ্ঞতা", "অ্যানালিটিক্স"]'::jsonb, progression_bn = '[{"label": "ই-কমার্স সহকারী", "time": "0–1 yr"}, {"label": "ই-কমার্স ব্যবস্থাপক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ম্যানেজার", "time": "3–5 yrs"}, {"label": "ই-কমার্স প্রধান", "time": "5–8 yrs"}, {"label": "ভিপি অব ডিজিটাল কমার্স", "time": "8+ yrs"}]'::jsonb WHERE id = 39;
UPDATE career_paths SET title_bn = 'ম্যানেজমেন্ট ট্রেইনি', skills_bn = '["নেতৃত্ব", "সমস্যা সমাধান", "বিশ্লেষণাত্মক চিন্তাভাবনা", "যোগাযোগ", "দলগত কাজ"]'::jsonb, progression_bn = '[{"label": "ম্যানেজমেন্ট ট্রেইনি", "time": "0–1 yr", "current": true}, {"label": "সহকারী ব্যবস্থাপক", "time": "1–3 yrs"}, {"label": "উপ-ব্যবস্থাপক", "time": "3–5 yrs"}, {"label": "ব্যবস্থাপক", "time": "5–8 yrs"}, {"label": "পরিচালক", "time": "8+ yrs"}]'::jsonb WHERE id = 40;
UPDATE career_paths SET title_bn = 'গবেষণা সহযোগী', skills_bn = '["গবেষণা পদ্ধতি", "ডেটা বিশ্লেষণ", "বৈজ্ঞানিক লেখা", "ল্যাব কৌশল", "পরিসংখ্যান"]'::jsonb, progression_bn = '[{"label": "গবেষণা সহকারী", "time": "0–2 yrs"}, {"label": "গবেষণা সহযোগী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র গবেষক", "time": "4–7 yrs"}, {"label": "গবেষণা বিজ্ঞানী", "time": "7–10 yrs"}, {"label": "প্রিন্সিপাল সায়েন্টিস্ট", "time": "10+ yrs"}]'::jsonb WHERE id = 41;
UPDATE career_paths SET title_bn = 'বায়োমেডিকেল বিজ্ঞানী', skills_bn = '["ল্যাব পরীক্ষা", "মাইক্রোস্কোপি", "প্যাথলজি", "মান নিয়ন্ত্রণ", "চিকিৎসা পরিভাষা"]'::jsonb, progression_bn = '[{"label": "ল্যাব সহকারী", "time": "0–2 yrs"}, {"label": "বায়োমেডিকেল বিজ্ঞানী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র বিজ্ঞানী", "time": "4–7 yrs"}, {"label": "ল্যাব ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "ল্যাব সার্ভিসেস পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 42;
UPDATE career_paths SET title_bn = 'মান নিয়ন্ত্রণ কর্মকর্তা', skills_bn = '["GMP মানদণ্ড", "ল্যাব পরীক্ষা", "ডকুমেন্টেশন", "বিশ্লেষণাত্মক রসায়ন", "খুঁটিনাটি বিষয়ে মনোযোগ"]'::jsonb, progression_bn = '[{"label": "কিউসি ট্রেইনি", "time": "0–2 yrs"}, {"label": "কিউসি কর্মকর্তা", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র কিউসি কর্মকর্তা", "time": "4–7 yrs"}, {"label": "কিউসি ম্যানেজার", "time": "7–10 yrs"}, {"label": "কোয়ালিটি ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 43;
UPDATE career_paths SET title_bn = 'পরিবেশ বিজ্ঞানী', skills_bn = '["মাঠ নমুনা সংগ্রহ", "ডেটা বিশ্লেষণ", "পরিবেশ আইন", "রিপোর্ট লেখা", "GIS"]'::jsonb, progression_bn = '[{"label": "মাঠ সহকারী", "time": "0–2 yrs"}, {"label": "পরিবেশ বিজ্ঞানী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র বিজ্ঞানী", "time": "4–7 yrs"}, {"label": "প্রকল্প ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 44;
UPDATE career_paths SET title_bn = 'অণুজীববিজ্ঞানী', skills_bn = '["কালচার পদ্ধতি", "জীবাণুমুক্তকরণ", "মাইক্রোস্কোপি", "ল্যাব নিরাপত্তা", "ডেটা লিপিবদ্ধকরণ"]'::jsonb, progression_bn = '[{"label": "ল্যাব টেকনিশিয়ান", "time": "0–2 yrs"}, {"label": "অণুজীববিজ্ঞানী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র অণুজীববিজ্ঞানী", "time": "4–7 yrs"}, {"label": "ল্যাব ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "সায়েন্টিফিক ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 45;
UPDATE career_paths SET title_bn = 'খাদ্য বিজ্ঞানী', skills_bn = '["খাদ্য নিরাপত্তা", "পণ্য উন্নয়ন", "মান নিশ্চয়তা", "সংবেদনশীল মূল্যায়ন", "বিধিমালা"]'::jsonb, progression_bn = '[{"label": "কোয়ালিটি ট্রেইনি", "time": "0–2 yrs"}, {"label": "খাদ্য বিজ্ঞানী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র খাদ্য বিজ্ঞানী", "time": "4–7 yrs"}, {"label": "R&D ম্যানেজার", "time": "7–10 yrs"}, {"label": "টেকনিক্যাল ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 46;
UPDATE career_paths SET title_bn = 'জেনেটিক কাউন্সেলর', skills_bn = '["জিনতত্ত্ব জ্ঞান", "রোগী কাউন্সেলিং", "ঝুঁকি মূল্যায়ন", "চিকিৎসা নৈতিকতা", "যোগাযোগ"]'::jsonb, progression_bn = '[{"label": "জেনেটিক সহকারী", "time": "0–2 yrs"}, {"label": "জেনেটিক কাউন্সেলর", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র কাউন্সেলর", "time": "4–7 yrs"}, {"label": "ক্লিনিক ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "জেনেটিক্স পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 47;
UPDATE career_paths SET title_bn = 'কৃষিবিজ্ঞানী', skills_bn = '["ফসল বিজ্ঞান", "মাটি ব্যবস্থাপনা", "পোকামাকড় নিয়ন্ত্রণ", "মাঠ গবেষণা", "কৃষক প্রশিক্ষণ"]'::jsonb, progression_bn = '[{"label": "মাঠ কর্মকর্তা", "time": "0–2 yrs"}, {"label": "কৃষিবিজ্ঞানী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র কৃষিবিজ্ঞানী", "time": "4–7 yrs"}, {"label": "কৃষি ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "কৃষি পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 48;
UPDATE career_paths SET title_bn = 'মৎস্য কর্মকর্তা', skills_bn = '["মৎস্যচাষ", "মাছের স্বাস্থ্য", "পানির গুণমান", "মজুদ মূল্যায়ন", "নিয়ন্ত্রক সম্মতি"]'::jsonb, progression_bn = '[{"label": "মৎস্য সহকারী", "time": "0–2 yrs"}, {"label": "মৎস্য কর্মকর্তা", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র কর্মকর্তা", "time": "4–7 yrs"}, {"label": "মৎস্য ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "মৎস্য পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 49;
UPDATE career_paths SET title_bn = 'ক্লিনিক্যাল গবেষণা সমন্বয়কারী', skills_bn = '["GCP নির্দেশিকা", "রোগী নিয়োগ", "ডেটা সংগ্রহ", "নিয়ন্ত্রক সম্মতি", "নৈতিকতা"]'::jsonb, progression_bn = '[{"label": "সিআরসি ট্রেইনি", "time": "0–2 yrs"}, {"label": "ক্লিনিক্যাল গবেষণা সমন্বয়কারী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র সিআরসি", "time": "4–7 yrs"}, {"label": "ক্লিনিক্যাল প্রকল্প ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "ক্লিনিক্যাল অপারেশনস ডিরেক্টর", "time": "10+ yrs"}]'::jsonb WHERE id = 50;
UPDATE career_paths SET title_bn = 'কনটেন্ট রাইটার', skills_bn = '["সৃজনশীল লেখা", "SEO", "গবেষণা", "ব্যাকরণ", "কনটেন্ট কৌশল"]'::jsonb, progression_bn = '[{"label": "জুনিয়র লেখক", "time": "0–1 yr"}, {"label": "কনটেন্ট রাইটার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র লেখক", "time": "3–5 yrs"}, {"label": "কনটেন্ট ম্যানেজার", "time": "5–8 yrs"}, {"label": "এডিটোরিয়াল ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 51;
UPDATE career_paths SET title_bn = 'গ্রাফিক ডিজাইনার', skills_bn = '["Adobe Photoshop", "Illustrator", "টাইপোগ্রাফি", "ব্র্যান্ডিং", "Figma"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ডিজাইনার", "time": "0–1 yr"}, {"label": "গ্রাফিক ডিজাইনার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ডিজাইনার", "time": "3–5 yrs"}, {"label": "আর্ট ডিরেক্টর", "time": "5–8 yrs"}, {"label": "ক্রিয়েটিভ ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 52;
UPDATE career_paths SET title_bn = 'সাংবাদিক', skills_bn = '["রিপোর্টিং", "সাক্ষাৎকার গ্রহণ", "তথ্য যাচাই", "লেখা", "নৈতিকতা"]'::jsonb, progression_bn = '[{"label": "রিপোর্টার", "time": "0–1 yr"}, {"label": "সাংবাদিক", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র রিপোর্টার", "time": "3–5 yrs"}, {"label": "নিউজ এডিটর", "time": "5–8 yrs"}, {"label": "প্রধান সম্পাদক", "time": "8+ yrs"}]'::jsonb WHERE id = 53;
UPDATE career_paths SET title_bn = 'জনসংযোগ কর্মকর্তা', skills_bn = '["গণমাধ্যম সম্পর্ক", "প্রেস রিলিজ লেখা", "সংকট যোগাযোগ", "ইভেন্ট পরিকল্পনা", "নেটওয়ার্কিং"]'::jsonb, progression_bn = '[{"label": "পিআর সহকারী", "time": "0–1 yr"}, {"label": "পিআরও", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র পিআরও", "time": "3–5 yrs"}, {"label": "পিআর ম্যানেজার", "time": "5–8 yrs"}, {"label": "কমিউনিকেশনস ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 54;
UPDATE career_paths SET title_bn = 'সোশ্যাল মিডিয়া ম্যানেজার', skills_bn = '["Instagram/Facebook/LinkedIn", "কনটেন্ট ক্যালেন্ডার", "অ্যানালিটিক্স", "কমিউনিটি ব্যবস্থাপনা", "Canva"]'::jsonb, progression_bn = '[{"label": "সোশ্যাল মিডিয়া সহকারী", "time": "0–1 yr"}, {"label": "সোশ্যাল মিডিয়া ম্যানেজার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ম্যানেজার", "time": "3–5 yrs"}, {"label": "সোশ্যাল প্রধান", "time": "5–8 yrs"}, {"label": "ডিজিটাল মার্কেটিং ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 55;
UPDATE career_paths SET title_bn = 'ফটোগ্রাফার / ভিডিওগ্রাফার', skills_bn = '["ফটোগ্রাফি", "ভিডিও এডিটিং", "লাইটিং", "Adobe Suite", "গল্প বলা"]'::jsonb, progression_bn = '[{"label": "সহকারী ফটোগ্রাফার", "time": "0–1 yr"}, {"label": "ফটোগ্রাফার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ফটোগ্রাফার", "time": "3–5 yrs"}, {"label": "ক্রিয়েটিভ লিড", "time": "5–8 yrs"}, {"label": "ফটোগ্রাফি পরিচালক", "time": "8+ yrs"}]'::jsonb WHERE id = 56;
UPDATE career_paths SET title_bn = 'ইউএক্স/ইউআই ডিজাইনার', skills_bn = '["Figma", "ব্যবহারকারী গবেষণা", "ওয়্যারফ্রেমিং", "প্রোটোটাইপিং", "ব্যবহারযোগ্যতা পরীক্ষা"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ডিজাইনার", "time": "0–1 yr"}, {"label": "ইউএক্স/ইউআই ডিজাইনার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ডিজাইনার", "time": "3–5 yrs"}, {"label": "ডিজাইন লিড", "time": "5–8 yrs"}, {"label": "ডিজাইন প্রধান", "time": "8+ yrs"}]'::jsonb WHERE id = 57;
UPDATE career_paths SET title_bn = 'ইভেন্ট ম্যানেজার', skills_bn = '["ইভেন্ট পরিকল্পনা", "ভেন্ডর ব্যবস্থাপনা", "বাজেট প্রণয়ন", "লজিস্টিকস", "ক্লায়েন্ট যোগাযোগ"]'::jsonb, progression_bn = '[{"label": "ইভেন্ট সমন্বয়কারী", "time": "0–1 yr"}, {"label": "ইভেন্ট ম্যানেজার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র ম্যানেজার", "time": "3–5 yrs"}, {"label": "ইভেন্ট ডিরেক্টর", "time": "5–8 yrs"}, {"label": "ইভেন্ট প্রধান", "time": "8+ yrs"}]'::jsonb WHERE id = 58;
UPDATE career_paths SET title_bn = 'অনুবাদক (ইংরেজি-বাংলা)', skills_bn = '["ইংরেজিতে সাবলীলতা", "বাংলা লেখা", "অনুবাদ টুলস", "প্রুফরিডিং", "সাংস্কৃতিক জ্ঞান"]'::jsonb, progression_bn = '[{"label": "অনুবাদক", "time": "0–2 yrs", "current": true}, {"label": "সিনিয়র অনুবাদক", "time": "2–4 yrs"}, {"label": "অনুবাদ সম্পাদক", "time": "4–6 yrs"}, {"label": "ল্যাঙ্গুয়েজ লিড", "time": "6–8 yrs"}, {"label": "লোকালাইজেশন ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 59;
UPDATE career_paths SET title_bn = 'কপিরাইটার', skills_bn = '["সৃজনশীল লেখা", "ব্র্যান্ডের কণ্ঠস্বর", "হেডলাইন", "গল্প বলা", "ক্যাম্পেইন কৌশল"]'::jsonb, progression_bn = '[{"label": "জুনিয়র কপিরাইটার", "time": "0–1 yr"}, {"label": "কপিরাইটার", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র কপিরাইটার", "time": "3–5 yrs"}, {"label": "কপি চিফ", "time": "5–8 yrs"}, {"label": "ক্রিয়েটিভ ডিরেক্টর", "time": "8+ yrs"}]'::jsonb WHERE id = 60;
UPDATE career_paths SET title_bn = 'স্কুল শিক্ষক', skills_bn = '["পাঠ পরিকল্পনা", "শ্রেণিকক্ষ ব্যবস্থাপনা", "বিষয়ভিত্তিক দক্ষতা", "যোগাযোগ", "ধৈর্য"]'::jsonb, progression_bn = '[{"label": "সহকারী শিক্ষক", "time": "0–2 yrs"}, {"label": "শিক্ষক", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র শিক্ষক", "time": "4–7 yrs"}, {"label": "বিভাগীয় প্রধান", "time": "7–10 yrs"}, {"label": "প্রিন্সিপাল", "time": "10+ yrs"}]'::jsonb WHERE id = 61;
UPDATE career_paths SET title_bn = 'শিক্ষা কর্মসূচি কর্মকর্তা', skills_bn = '["প্রকল্প ব্যবস্থাপনা", "পর্যবেক্ষণ ও মূল্যায়ন", "রিপোর্ট লেখা", "সম্প্রদায় সম্পৃক্ততা", "ডেটা বিশ্লেষণ"]'::jsonb, progression_bn = '[{"label": "প্রোগ্রাম সহকারী", "time": "0–1 yr"}, {"label": "প্রোগ্রাম কর্মকর্তা", "time": "1–3 yrs", "current": true}, {"label": "সিনিয়র কর্মকর্তা", "time": "3–5 yrs"}, {"label": "প্রোগ্রাম ম্যানেজার", "time": "5–8 yrs"}, {"label": "পরিচালক", "time": "8+ yrs"}]'::jsonb WHERE id = 62;
UPDATE career_paths SET title_bn = 'পাঠ্যক্রম উন্নয়নকারী', skills_bn = '["পাঠ্যক্রম ডিজাইন", "শিক্ষা তত্ত্ব", "কনটেন্ট লেখা", "মূল্যায়ন ডিজাইন", "গবেষণা"]'::jsonb, progression_bn = '[{"label": "পাঠ্যক্রম সহকারী", "time": "0–2 yrs"}, {"label": "পাঠ্যক্রম উন্নয়নকারী", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র ডেভেলপার", "time": "4–7 yrs"}, {"label": "পাঠ্যক্রম ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "পাঠ্যক্রম প্রধান", "time": "10+ yrs"}]'::jsonb WHERE id = 63;
UPDATE career_paths SET title_bn = 'শিক্ষা পরামর্শদাতা', skills_bn = '["কাউন্সেলিং", "ক্যারিয়ার নির্দেশনা", "বিশ্ববিদ্যালয় ভর্তি", "যোগাযোগ", "সমস্যা সমাধান"]'::jsonb, progression_bn = '[{"label": "কাউন্সেলিং সহকারী", "time": "0–2 yrs"}, {"label": "শিক্ষা পরামর্শদাতা", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র পরামর্শদাতা", "time": "4–7 yrs"}, {"label": "প্রধান পরামর্শদাতা", "time": "7–10 yrs"}, {"label": "স্টুডেন্ট সার্ভিসেস পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 64;
UPDATE career_paths SET title_bn = 'ইনস্ট্রাকশনাল ডিজাইনার', skills_bn = '["ই-লার্নিং টুলস", "Articulate Storyline", "ইনস্ট্রাকশনাল ডিজাইন মডেল", "মাল্টিমিডিয়া", "মূল্যায়ন"]'::jsonb, progression_bn = '[{"label": "জুনিয়র ইনস্ট্রাকশনাল ডিজাইনার", "time": "0–2 yrs"}, {"label": "ইনস্ট্রাকশনাল ডিজাইনার", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র ইনস্ট্রাকশনাল ডিজাইনার", "time": "4–7 yrs"}, {"label": "লার্নিং এক্সপেরিয়েন্স ম্যানেজার", "time": "7–10 yrs"}, {"label": "লার্নিং ডিজাইন প্রধান", "time": "10+ yrs"}]'::jsonb WHERE id = 65;
UPDATE career_paths SET title_bn = 'বিশ্ববিদ্যালয়ের প্রভাষক', skills_bn = '["শিক্ষকতা", "গবেষণা", "একাডেমিক লেখা", "জনসমক্ষে বক্তৃতা", "বিষয়ে দক্ষতা"]'::jsonb, progression_bn = '[{"label": "প্রভাষক", "time": "0–3 yrs", "current": true}, {"label": "সিনিয়র প্রভাষক", "time": "3–6 yrs"}, {"label": "সহকারী অধ্যাপক", "time": "6–9 yrs"}, {"label": "সহযোগী অধ্যাপক", "time": "9–12 yrs"}, {"label": "অধ্যাপক", "time": "12+ yrs"}]'::jsonb WHERE id = 66;
UPDATE career_paths SET title_bn = 'বিশেষ শিক্ষা শিক্ষক', skills_bn = '["ব্যক্তিগত শিক্ষা পরিকল্পনা", "আচরণ ব্যবস্থাপনা", "সহায়ক প্রযুক্তি", "ধৈর্য", "অভিযোজন"]'::jsonb, progression_bn = '[{"label": "বিশেষ শিক্ষা সহকারী", "time": "0–2 yrs"}, {"label": "বিশেষ শিক্ষা শিক্ষক", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র শিক্ষক", "time": "4–7 yrs"}, {"label": "বিশেষ শিক্ষা সমন্বয়কারী", "time": "7–10 yrs"}, {"label": "বিশেষ শিক্ষা পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 67;
UPDATE career_paths SET title_bn = 'শিক্ষা প্রযুক্তি বিশেষজ্ঞ', skills_bn = '["LMS ব্যবস্থাপনা", "শিক্ষক প্রশিক্ষণ", "কারিগরি সহায়তা", "শিক্ষা প্রযুক্তি", "প্রকল্প ব্যবস্থাপনা"]'::jsonb, progression_bn = '[{"label": "এডটেক সহকারী", "time": "0–2 yrs"}, {"label": "এডটেক বিশেষজ্ঞ", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র বিশেষজ্ঞ", "time": "4–7 yrs"}, {"label": "এডটেক ব্যবস্থাপক", "time": "7–10 yrs"}, {"label": "ডিজিটাল লার্নিং পরিচালক", "time": "10+ yrs"}]'::jsonb WHERE id = 68;
UPDATE career_paths SET title_bn = 'প্রশিক্ষণ সমন্বয়কারী', skills_bn = '["প্রশিক্ষণ লজিস্টিকস", "চাহিদা মূল্যায়ন", "ভেন্ডর ব্যবস্থাপনা", "বাজেট প্রণয়ন", "যোগাযোগ"]'::jsonb, progression_bn = '[{"label": "প্রশিক্ষণ সহকারী", "time": "0–2 yrs"}, {"label": "প্রশিক্ষণ সমন্বয়কারী", "time": "2–4 yrs", "current": true}, {"label": "প্রশিক্ষণ ব্যবস্থাপক", "time": "4–7 yrs"}, {"label": "লার্নিং অ্যান্ড ডেভেলপমেন্ট ম্যানেজার", "time": "7–10 yrs"}, {"label": "চিফ লার্নিং অফিসার", "time": "10+ yrs"}]'::jsonb WHERE id = 69;
UPDATE career_paths SET title_bn = 'প্রাক-প্রাথমিক শিক্ষক', skills_bn = '["শিশু বিকাশ", "খেলাভিত্তিক শিখন", "শ্রেণিকক্ষ ব্যবস্থাপনা", "অভিভাবক যোগাযোগ", "সৃজনশীলতা"]'::jsonb, progression_bn = '[{"label": "সহকারী শিক্ষক", "time": "0–2 yrs"}, {"label": "প্রধান শিক্ষক", "time": "2–4 yrs", "current": true}, {"label": "সিনিয়র শিক্ষক", "time": "4–7 yrs"}, {"label": "প্রি-স্কুল ডিরেক্টর", "time": "7–10 yrs"}, {"label": "প্রাক-শৈশব পরামর্শক", "time": "10+ yrs"}]'::jsonb WHERE id = 70;

-- ── alumni ──────────────────────────────────────────────────────────────
UPDATE alumni SET full_name_bn = 'সাদিয়া রহমান', institution_bn = 'বুয়েট', current_role_bn = 'সফটওয়্যার প্রকৌশলী' WHERE id = 1;
UPDATE alumni SET full_name_bn = 'রাকিব হাসান', institution_bn = 'নর্থ সাউথ ইউনিভার্সিটি', current_role_bn = 'আর্থিক বিশ্লেষক' WHERE id = 2;
UPDATE alumni SET full_name_bn = 'তানিয়া আক্তার', institution_bn = 'ঢাকা বিশ্ববিদ্যালয়', current_role_bn = 'গবেষণা সহযোগী' WHERE id = 3;
UPDATE alumni SET full_name_bn = 'মেহেদী ইসলাম', institution_bn = 'রুয়েট', current_role_bn = 'প্রকল্প ব্যবস্থাপক' WHERE id = 4;
UPDATE alumni SET full_name_bn = 'নুসরাত জাহান', institution_bn = 'চট্টগ্রাম বিশ্ববিদ্যালয়', current_role_bn = 'মার্কেটিং নির্বাহী' WHERE id = 5;
UPDATE alumni SET full_name_bn = 'আরিফ চৌধুরী', institution_bn = 'আইইউবি', current_role_bn = 'ফ্রন্টএন্ড ডেভেলপার' WHERE id = 6;
UPDATE alumni SET full_name_bn = 'ফারজানা হক', institution_bn = 'জাহাঙ্গীরনগর বিশ্ববিদ্যালয়', current_role_bn = 'কনটেন্ট স্ট্র্যাটেজিস্ট' WHERE id = 7;
UPDATE alumni SET full_name_bn = 'শাহিদ খান', institution_bn = 'ব্র্যাক বিশ্ববিদ্যালয়', current_role_bn = 'ম্যানেজমেন্ট ট্রেইনি' WHERE id = 8;
UPDATE alumni SET full_name_bn = 'মৌমিতা দাস', institution_bn = 'বুয়েট', current_role_bn = 'সিভিল প্রকৌশলী' WHERE id = 9;
UPDATE alumni SET full_name_bn = 'ইমরান হোসাইন', institution_bn = 'ঢাকা বিশ্ববিদ্যালয়', current_role_bn = 'মান নিয়ন্ত্রণ কর্মকর্তা' WHERE id = 10;

COMMIT;
