-- Module: seed_content_data
-- Seeds the four content tables with the curated Bangladesh-market dataset.
--
-- Source: the JSON datasets from the isar-frontend-data branch, converted to SQL.
-- Curated by Isar (dwijeshu003@gmail.com); the underlying research is theirs.
--
-- Idempotent: every statement is ON CONFLICT DO NOTHING and explicit ids are
-- preserved so cross-page links by id keep working. Sequences are re-synced
-- at the end so subsequent admin inserts do not collide with seeded ids.
--
-- Resource Bangla columns are intentionally NULL: the curated content is
-- English-only and Bangla translations are entered via the admin dashboard.

-- disciplines (7 rows)
INSERT INTO disciplines (id, name, description) VALUES
  (1, 'IT', 'Information Technology and Computer Science'),
  (2, 'Finance', 'Banking, Accounting, and Financial Services'),
  (3, 'Science', 'Pure and Applied Sciences'),
  (4, 'Engineering', 'Civil, Electrical, Mechanical and related'),
  (5, 'Business', 'Marketing, Management, and Commerce'),
  (6, 'Arts', 'Humanities, Social Sciences, and Creative Arts'),
  (7, 'Education', 'Teaching and Educational Leadership')
ON CONFLICT (id) DO NOTHING;

-- career_paths (70 rows)
INSERT INTO career_paths (id, title, industry, discipline, description, skills, progression, salary_entry, salary_senior) VALUES
  (1, 'Financial Analyst', 'Banking and Finance', 'Finance', 'Financial Analysts in Bangladesh are in high demand across banks, NGOs, and corporate finance teams. The role involves analysing financial data, preparing reports, and supporting business decisions.', '["Excel","Financial Modelling","Accounting","Data Analysis","Report Writing"]'::jsonb, '[{"label":"Junior Analyst","time":"0–1 yr"},{"label":"Financial Analyst","time":"1–3 yrs","current":true},{"label":"Senior Analyst","time":"3–5 yrs"},{"label":"Finance Manager","time":"5–8 yrs"},{"label":"CFO","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–40,000', 'BDT 80,000–150,000'),
  (2, 'Bank Relationship Officer', 'Banking', 'Finance', 'Relationship officers manage client accounts, process loans, and provide customer service at banks like Dutch-Bangla, BRAC Bank, and City Bank.', '["Customer Service","Loan Processing","CRM Software","Communication","Sales"]'::jsonb, '[{"label":"Trainee Officer","time":"0–1 yr"},{"label":"Relationship Officer","time":"1–3 yrs","current":true},{"label":"Senior Officer","time":"3–5 yrs"},{"label":"Branch Manager","time":"5–8 yrs"},{"label":"Regional Manager","time":"8+ yrs"}]'::jsonb, 'BDT 22,000–35,000', 'BDT 70,000–120,000'),
  (3, 'Audit Associate', 'Auditing', 'Finance', 'Audit associates work at firms like ACNABIN, Rahman Rahman Huq, and KPMG Bangladesh, checking financial records for accuracy and compliance.', '["Auditing Standards","Attention to Detail","Accounting Software","Analytical Thinking","Report Writing"]'::jsonb, '[{"label":"Audit Trainee","time":"0–1 yr"},{"label":"Audit Associate","time":"1–3 yrs","current":true},{"label":"Senior Auditor","time":"3–5 yrs"},{"label":"Audit Manager","time":"5–8 yrs"},{"label":"Partner","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–32,000', 'BDT 80,000–150,000'),
  (4, 'Tax Consultant', 'Taxation', 'Finance', 'Tax consultants help individuals and companies file taxes, plan tax strategies, and comply with Bangladesh tax laws.', '["Tax Laws","Compliance","Client Management","Analytical Skills","Communication"]'::jsonb, '[{"label":"Tax Trainee","time":"0–1 yr"},{"label":"Tax Consultant","time":"1–3 yrs","current":true},{"label":"Senior Consultant","time":"3–5 yrs"},{"label":"Tax Manager","time":"5–8 yrs"},{"label":"Tax Partner","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–38,000', 'BDT 90,000–180,000'),
  (5, 'Investment Analyst', 'Investment', 'Finance', 'Investment analysts research stocks, bonds, and other investments for brokerage firms and asset management companies in Bangladesh.', '["Financial Research","Stock Market","Valuation","Bloomberg Terminal","Risk Assessment"]'::jsonb, '[{"label":"Research Assistant","time":"0–1 yr"},{"label":"Investment Analyst","time":"1–3 yrs","current":true},{"label":"Senior Analyst","time":"3–5 yrs"},{"label":"Portfolio Manager","time":"5–8 yrs"},{"label":"Investment Director","time":"8+ yrs"}]'::jsonb, 'BDT 30,000–45,000', 'BDT 100,000–200,000'),
  (6, 'Credit Risk Officer', 'Risk Management', 'Finance', 'Credit risk officers evaluate loan applications, assess borrower risk, and set credit limits for banks and financial institutions.', '["Risk Assessment","Credit Scoring","Financial Analysis","Regulatory Knowledge","Decision Making"]'::jsonb, '[{"label":"Credit Trainee","time":"0–1 yr"},{"label":"Credit Officer","time":"1–3 yrs","current":true},{"label":"Senior Credit Officer","time":"3–5 yrs"},{"label":"Credit Manager","time":"5–8 yrs"},{"label":"Chief Risk Officer","time":"8+ yrs"}]'::jsonb, 'BDT 28,000–42,000', 'BDT 90,000–160,000'),
  (7, 'Accounts Executive', 'Accounting', 'Finance', 'Accounts executives manage day-to-day bookkeeping, prepare financial statements, and handle accounts payable/receivable for companies.', '["Bookkeeping","Tally/QuickBooks","Invoice Processing","Reconciliation","Financial Reporting"]'::jsonb, '[{"label":"Accounts Assistant","time":"0–1 yr"},{"label":"Accounts Executive","time":"1–3 yrs","current":true},{"label":"Senior Accountant","time":"3–5 yrs"},{"label":"Finance Controller","time":"5–8 yrs"},{"label":"Finance Director","time":"8+ yrs"}]'::jsonb, 'BDT 18,000–30,000', 'BDT 60,000–100,000'),
  (8, 'Treasury Analyst', 'Treasury', 'Finance', 'Treasury analysts manage company cash flow, foreign exchange exposure, and banking relationships for large corporations in Bangladesh.', '["Cash Management","Forex","Banking","Excel","Financial Markets"]'::jsonb, '[{"label":"Treasury Assistant","time":"0–1 yr"},{"label":"Treasury Analyst","time":"1–3 yrs","current":true},{"label":"Senior Treasury Analyst","time":"3–5 yrs"},{"label":"Treasury Manager","time":"5–8 yrs"},{"label":"Group Treasurer","time":"8+ yrs"}]'::jsonb, 'BDT 30,000–50,000', 'BDT 100,000–180,000'),
  (9, 'Microfinance Officer', 'Microfinance', 'Finance', 'Microfinance officers work with NGOs like BRAC, ASA, and Grameen Bank to provide small loans to rural entrepreneurs.', '["Field Work","Client Assessment","Loan Recovery","Community Relations","Documentation"]'::jsonb, '[{"label":"Field Officer","time":"0–1 yr"},{"label":"Microfinance Officer","time":"1–3 yrs","current":true},{"label":"Branch Manager","time":"3–5 yrs"},{"label":"Area Manager","time":"5–8 yrs"},{"label":"Regional Director","time":"8+ yrs"}]'::jsonb, 'BDT 15,000–25,000', 'BDT 50,000–80,000'),
  (10, 'Insurance Underwriter', 'Insurance', 'Finance', 'Underwriters evaluate insurance applications, assess risk, and determine coverage amounts for life, health, and property insurance.', '["Risk Assessment","Insurance Policies","Data Analysis","Medical Terminology","Legal Knowledge"]'::jsonb, '[{"label":"Underwriting Trainee","time":"0–1 yr"},{"label":"Underwriter","time":"1–3 yrs","current":true},{"label":"Senior Underwriter","time":"3–5 yrs"},{"label":"Underwriting Manager","time":"5–8 yrs"},{"label":"Chief Underwriter","time":"8+ yrs"}]'::jsonb, 'BDT 22,000–35,000', 'BDT 70,000–130,000'),
  (11, 'Software Engineer', 'Technology', 'IT', 'Software engineers design, code, and maintain applications for companies like Pathao, Shohoz, and numerous software outsourcing firms in Bangladesh.', '["JavaScript","React","Node.js","PostgreSQL","Git","REST APIs"]'::jsonb, '[{"label":"Junior Developer","time":"0–1 yr"},{"label":"Software Engineer","time":"1–3 yrs","current":true},{"label":"Senior Engineer","time":"3–6 yrs"},{"label":"Tech Lead","time":"6–9 yrs"},{"label":"CTO","time":"9+ yrs"}]'::jsonb, 'BDT 30,000–55,000', 'BDT 120,000–250,000'),
  (12, 'Frontend Developer', 'Technology', 'IT', 'Frontend developers build user interfaces for websites and web applications using HTML, CSS, and JavaScript frameworks.', '["React","Vue.js","HTML/CSS","JavaScript","Responsive Design","Figma"]'::jsonb, '[{"label":"Junior Frontend","time":"0–1 yr"},{"label":"Frontend Developer","time":"1–3 yrs","current":true},{"label":"Senior Frontend","time":"3–5 yrs"},{"label":"Frontend Lead","time":"5–8 yrs"},{"label":"UI/UX Director","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–45,000', 'BDT 100,000–200,000'),
  (13, 'Backend Developer', 'Technology', 'IT', 'Backend developers build server-side logic, databases, and APIs that power web and mobile applications.', '["Python/Django","Node.js","SQL","API Design","Server Management","Security"]'::jsonb, '[{"label":"Junior Backend","time":"0–1 yr"},{"label":"Backend Developer","time":"1–3 yrs","current":true},{"label":"Senior Backend","time":"3–5 yrs"},{"label":"Backend Architect","time":"5–8 yrs"},{"label":"Engineering Manager","time":"8+ yrs"}]'::jsonb, 'BDT 28,000–50,000', 'BDT 110,000–220,000'),
  (14, 'DevOps Engineer', 'Technology', 'IT', 'DevOps engineers manage deployment pipelines, cloud infrastructure, and system reliability for tech companies.', '["AWS/GCP","Docker","Kubernetes","CI/CD","Linux","Monitoring Tools"]'::jsonb, '[{"label":"Junior DevOps","time":"0–1 yr"},{"label":"DevOps Engineer","time":"1–3 yrs","current":true},{"label":"Senior DevOps","time":"3–5 yrs"},{"label":"Platform Architect","time":"5–8 yrs"},{"label":"Head of Infrastructure","time":"8+ yrs"}]'::jsonb, 'BDT 35,000–60,000', 'BDT 130,000–250,000'),
  (15, 'Data Analyst', 'Data', 'IT', 'Data analysts collect, process, and analyse data to help businesses make informed decisions.', '["SQL","Python","Excel","Tableau","Statistical Analysis","Data Visualization"]'::jsonb, '[{"label":"Junior Data Analyst","time":"0–1 yr"},{"label":"Data Analyst","time":"1–3 yrs","current":true},{"label":"Senior Data Analyst","time":"3–5 yrs"},{"label":"Data Scientist","time":"5–8 yrs"},{"label":"Head of Data","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–45,000', 'BDT 100,000–200,000'),
  (16, 'QA Engineer', 'Quality Assurance', 'IT', 'QA engineers test software, find bugs, and ensure product quality before release.', '["Manual Testing","Automation","Selenium","Bug Tracking","Test Cases","Attention to Detail"]'::jsonb, '[{"label":"Junior QA","time":"0–1 yr"},{"label":"QA Engineer","time":"1–3 yrs","current":true},{"label":"Senior QA","time":"3–5 yrs"},{"label":"QA Lead","time":"5–8 yrs"},{"label":"QA Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 80,000–150,000'),
  (17, 'Database Administrator', 'Database', 'IT', 'DBAs manage, secure, and optimise databases for organisations.', '["PostgreSQL","MySQL","MongoDB","Backup/Recovery","Performance Tuning","Security"]'::jsonb, '[{"label":"Junior DBA","time":"0–1 yr"},{"label":"DBA","time":"1–3 yrs","current":true},{"label":"Senior DBA","time":"3–5 yrs"},{"label":"Database Architect","time":"5–8 yrs"},{"label":"Data Platform Lead","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–45,000', 'BDT 100,000–180,000'),
  (18, 'Cybersecurity Analyst', 'Security', 'IT', 'Cybersecurity analysts protect organisations from cyber threats, monitor systems, and respond to incidents.', '["Network Security","Vulnerability Assessment","SIEM Tools","Risk Management","Ethical Hacking"]'::jsonb, '[{"label":"Security Trainee","time":"0–1 yr"},{"label":"Security Analyst","time":"1–3 yrs","current":true},{"label":"Senior Security Analyst","time":"3–5 yrs"},{"label":"Security Manager","time":"5–8 yrs"},{"label":"CISO","time":"8+ yrs"}]'::jsonb, 'BDT 30,000–55,000', 'BDT 120,000–250,000'),
  (19, 'IT Support Specialist', 'IT Support', 'IT', 'IT support specialists help users with technical issues, maintain hardware, and manage networks.', '["Hardware Troubleshooting","Networking","Windows/Linux","Customer Service","Ticketing Systems"]'::jsonb, '[{"label":"IT Support Level 1","time":"0–1 yr"},{"label":"IT Support Specialist","time":"1–3 yrs","current":true},{"label":"Senior IT Support","time":"3–5 yrs"},{"label":"IT Manager","time":"5–8 yrs"},{"label":"IT Director","time":"8+ yrs"}]'::jsonb, 'BDT 18,000–30,000', 'BDT 60,000–100,000'),
  (20, 'Mobile App Developer', 'Mobile Development', 'IT', 'Mobile developers build Android and iOS apps for Bangladeshi startups and enterprises.', '["Flutter","React Native","Android","iOS","App Store Deployment","REST APIs"]'::jsonb, '[{"label":"Junior Mobile Dev","time":"0–1 yr"},{"label":"Mobile Developer","time":"1–3 yrs","current":true},{"label":"Senior Mobile Dev","time":"3–5 yrs"},{"label":"Mobile Tech Lead","time":"5–8 yrs"},{"label":"Head of Mobile","time":"8+ yrs"}]'::jsonb, 'BDT 28,000–50,000', 'BDT 110,000–220,000'),
  (21, 'Civil Engineer', 'Construction', 'Engineering', 'Civil engineers design and oversee construction of roads, bridges, buildings, and infrastructure projects.', '["AutoCAD","Structural Analysis","Project Management","Site Supervision","Cost Estimation"]'::jsonb, '[{"label":"Site Engineer","time":"0–2 yrs"},{"label":"Civil Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Project Manager","time":"7–10 yrs"},{"label":"Chief Engineer","time":"10+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 70,000–130,000'),
  (22, 'Electrical Engineer', 'Power and Energy', 'Engineering', 'Electrical engineers design, test, and maintain electrical systems for buildings, factories, and power plants.', '["Circuit Design","Power Systems","AutoCAD Electrical","PLC Programming","Safety Standards"]'::jsonb, '[{"label":"Junior Engineer","time":"0–2 yrs"},{"label":"Electrical Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Project Manager","time":"7–10 yrs"},{"label":"Chief Engineer","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 65,000–120,000'),
  (23, 'Mechanical Engineer', 'Manufacturing', 'Engineering', 'Mechanical engineers design and maintain machinery, HVAC systems, and production equipment for factories.', '["SolidWorks","Thermodynamics","Manufacturing Processes","Maintenance","CAD"]'::jsonb, '[{"label":"Junior Engineer","time":"0–2 yrs"},{"label":"Mechanical Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Plant Manager","time":"7–10 yrs"},{"label":"Operations Director","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 65,000–120,000'),
  (24, 'Chemical Engineer', 'Pharmaceuticals', 'Engineering', 'Chemical engineers work in pharmaceutical, textile, and fertilizer plants, designing chemical processes.', '["Process Design","Safety Protocols","Quality Control","Thermodynamics","Lab Equipment"]'::jsonb, '[{"label":"Process Trainee","time":"0–2 yrs"},{"label":"Chemical Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Production Manager","time":"7–10 yrs"},{"label":"Plant Director","time":"10+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 70,000–130,000'),
  (25, 'Textile Engineer', 'Textile', 'Engineering', 'Textile engineers work in Bangladesh''s largest export industry, managing production and quality control.', '["Fabric Production","Quality Control","Dyeing Processes","Supply Chain","Factory Management"]'::jsonb, '[{"label":"Production Trainee","time":"0–2 yrs"},{"label":"Textile Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Production Manager","time":"7–10 yrs"},{"label":"Factory Director","time":"10+ yrs"}]'::jsonb, 'BDT 18,000–32,000', 'BDT 60,000–110,000'),
  (26, 'Industrial Engineer', 'Manufacturing', 'Engineering', 'Industrial engineers optimise production processes, reduce waste, and improve efficiency.', '["Process Optimization","Six Sigma","Supply Chain","Data Analysis","Lean Manufacturing"]'::jsonb, '[{"label":"Junior IE","time":"0–2 yrs"},{"label":"Industrial Engineer","time":"2–4 yrs","current":true},{"label":"Senior IE","time":"4–7 yrs"},{"label":"Operations Manager","time":"7–10 yrs"},{"label":"COO","time":"10+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 70,000–130,000'),
  (27, 'Environmental Engineer', 'Environment', 'Engineering', 'Environmental engineers work on waste management, pollution control, and sustainability projects.', '["Environmental Impact Assessment","Waste Management","Water Treatment","Compliance","Field Work"]'::jsonb, '[{"label":"Junior Engineer","time":"0–2 yrs"},{"label":"Environmental Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Project Manager","time":"7–10 yrs"},{"label":"Director of EHS","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 65,000–120,000'),
  (28, 'Telecommunication Engineer', 'Telecom', 'Engineering', 'Telecom engineers design and maintain mobile networks, fibre optics, and communication systems.', '["Network Design","RF Engineering","Fiber Optics","Signal Processing","Troubleshooting"]'::jsonb, '[{"label":"Network Trainee","time":"0–2 yrs"},{"label":"Telecom Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Network Manager","time":"7–10 yrs"},{"label":"CTO","time":"10+ yrs"}]'::jsonb, 'BDT 25,000–42,000', 'BDT 80,000–150,000'),
  (29, 'Automobile Engineer', 'Automotive', 'Engineering', 'Automobile engineers work in vehicle assembly, maintenance, and design for automotive companies.', '["Vehicle Systems","Diagnostics","CAD","Mechanical Repair","Quality Assurance"]'::jsonb, '[{"label":"Service Engineer","time":"0–2 yrs"},{"label":"Automobile Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Service Manager","time":"7–10 yrs"},{"label":"Operations Director","time":"10+ yrs"}]'::jsonb, 'BDT 18,000–32,000', 'BDT 60,000–110,000'),
  (30, 'Marine Engineer', 'Maritime', 'Engineering', 'Marine engineers work on ships, ports, and maritime operations in Chattogram and Dhaka.', '["Ship Systems","Marine Safety","Maintenance","Navigation Systems","Regulatory Compliance"]'::jsonb, '[{"label":"Junior Engineer","time":"0–2 yrs"},{"label":"Marine Engineer","time":"2–4 yrs","current":true},{"label":"Senior Engineer","time":"4–7 yrs"},{"label":"Chief Engineer","time":"7–10 yrs"},{"label":"Fleet Manager","time":"10+ yrs"}]'::jsonb, 'BDT 30,000–50,000', 'BDT 100,000–200,000'),
  (31, 'Marketing Executive', 'Marketing', 'Business', 'Marketing executives plan and execute campaigns, manage social media, and analyse market trends.', '["Digital Marketing","Social Media","Market Research","Campaign Management","Analytics"]'::jsonb, '[{"label":"Marketing Trainee","time":"0–1 yr"},{"label":"Marketing Executive","time":"1–3 yrs","current":true},{"label":"Senior Executive","time":"3–5 yrs"},{"label":"Brand Manager","time":"5–8 yrs"},{"label":"Marketing Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 80,000–160,000'),
  (32, 'HR Executive', 'Human Resources', 'Business', 'HR executives handle recruitment, onboarding, payroll, and employee relations.', '["Recruitment","Payroll","Labour Laws","Communication","Employee Engagement"]'::jsonb, '[{"label":"HR Trainee","time":"0–1 yr"},{"label":"HR Executive","time":"1–3 yrs","current":true},{"label":"Senior HR Executive","time":"3–5 yrs"},{"label":"HR Manager","time":"5–8 yrs"},{"label":"HR Director","time":"8+ yrs"}]'::jsonb, 'BDT 18,000–30,000', 'BDT 70,000–130,000'),
  (33, 'Business Development Officer', 'Sales', 'Business', 'BDOs identify new business opportunities, build client relationships, and drive revenue growth.', '["Sales","Negotiation","Client Relationship","Market Research","Communication"]'::jsonb, '[{"label":"Sales Trainee","time":"0–1 yr"},{"label":"BDO","time":"1–3 yrs","current":true},{"label":"Senior BDO","time":"3–5 yrs"},{"label":"Sales Manager","time":"5–8 yrs"},{"label":"Sales Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 80,000–200,000'),
  (34, 'Supply Chain Officer', 'Logistics', 'Business', 'Supply chain officers manage procurement, warehousing, and distribution for manufacturing and retail companies.', '["Procurement","Logistics","Inventory Management","Vendor Relations","ERP Systems"]'::jsonb, '[{"label":"Supply Chain Trainee","time":"0–1 yr"},{"label":"Supply Chain Officer","time":"1–3 yrs","current":true},{"label":"Senior Officer","time":"3–5 yrs"},{"label":"Supply Chain Manager","time":"5–8 yrs"},{"label":"Logistics Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 80,000–150,000'),
  (35, 'Operations Executive', 'Operations', 'Business', 'Operations executives ensure smooth day-to-day business operations and process efficiency.', '["Process Improvement","Team Management","Problem Solving","Reporting","Coordination"]'::jsonb, '[{"label":"Operations Trainee","time":"0–1 yr"},{"label":"Operations Executive","time":"1–3 yrs","current":true},{"label":"Senior Executive","time":"3–5 yrs"},{"label":"Operations Manager","time":"5–8 yrs"},{"label":"COO","time":"8+ yrs"}]'::jsonb, 'BDT 18,000–32,000', 'BDT 70,000–140,000'),
  (36, 'Export-Import Officer', 'International Trade', 'Business', 'Export-Import officers manage customs, documentation, and international shipping for trading companies.', '["Customs Documentation","LC Process","International Trade Laws","Freight Forwarding","Negotiation"]'::jsonb, '[{"label":"Trade Trainee","time":"0–1 yr"},{"label":"Export-Import Officer","time":"1–3 yrs","current":true},{"label":"Senior Officer","time":"3–5 yrs"},{"label":"Trade Manager","time":"5–8 yrs"},{"label":"Trade Director","time":"8+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 80,000–160,000'),
  (37, 'Customer Success Manager', 'Customer Service', 'Business', 'CSMs ensure customer satisfaction, retention, and loyalty for tech and service companies.', '["Customer Service","Problem Solving","Communication","CRM Software","Retention Strategies"]'::jsonb, '[{"label":"Customer Support","time":"0–1 yr"},{"label":"CSM","time":"1–3 yrs","current":true},{"label":"Senior CSM","time":"3–5 yrs"},{"label":"Customer Success Lead","time":"5–8 yrs"},{"label":"Head of Customer Success","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 80,000–150,000'),
  (38, 'Project Coordinator', 'Project Management', 'Business', 'Project coordinators help plan, track, and deliver projects across various industries.', '["Project Planning","MS Project","Communication","Risk Management","Budget Tracking"]'::jsonb, '[{"label":"Project Assistant","time":"0–1 yr"},{"label":"Project Coordinator","time":"1–3 yrs","current":true},{"label":"Project Manager","time":"3–5 yrs"},{"label":"Senior PM","time":"5–8 yrs"},{"label":"Program Director","time":"8+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 80,000–160,000'),
  (39, 'E-commerce Manager', 'E-commerce', 'Business', 'E-commerce managers oversee online stores, manage product listings, and drive sales for platforms like Daraz, Chaldal, and others.', '["E-commerce Platforms","Digital Marketing","Inventory Management","Customer Experience","Analytics"]'::jsonb, '[{"label":"E-commerce Assistant","time":"0–1 yr"},{"label":"E-commerce Manager","time":"1–3 yrs","current":true},{"label":"Senior Manager","time":"3–5 yrs"},{"label":"Head of E-commerce","time":"5–8 yrs"},{"label":"VP of Digital Commerce","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–45,000', 'BDT 100,000–200,000'),
  (40, 'Management Trainee', 'Management', 'Business', 'MT programs at Grameenphone, Unilever, BAT, and other multinationals train future leaders.', '["Leadership","Problem Solving","Analytical Thinking","Communication","Teamwork"]'::jsonb, '[{"label":"Management Trainee","time":"0–1 yr","current":true},{"label":"Assistant Manager","time":"1–3 yrs"},{"label":"Deputy Manager","time":"3–5 yrs"},{"label":"Manager","time":"5–8 yrs"},{"label":"Director","time":"8+ yrs"}]'::jsonb, 'BDT 40,000–60,000', 'BDT 150,000–250,000'),
  (41, 'Research Associate', 'Research', 'Science', 'Research associates work at icddr,b, BARI, BRRI, and university research centres.', '["Research Methodology","Data Analysis","Scientific Writing","Lab Techniques","Statistics"]'::jsonb, '[{"label":"Research Assistant","time":"0–2 yrs"},{"label":"Research Associate","time":"2–4 yrs","current":true},{"label":"Senior Researcher","time":"4–7 yrs"},{"label":"Research Scientist","time":"7–10 yrs"},{"label":"Principal Scientist","time":"10+ yrs"}]'::jsonb, 'BDT 25,000–42,000', 'BDT 75,000–140,000'),
  (42, 'Biomedical Scientist', 'Healthcare', 'Science', 'Biomedical scientists work in hospital labs, diagnostic centres, and pharmaceutical companies.', '["Lab Testing","Microscopy","Pathology","Quality Control","Medical Terminology"]'::jsonb, '[{"label":"Lab Assistant","time":"0–2 yrs"},{"label":"Biomedical Scientist","time":"2–4 yrs","current":true},{"label":"Senior Scientist","time":"4–7 yrs"},{"label":"Lab Manager","time":"7–10 yrs"},{"label":"Director of Lab Services","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 60,000–110,000'),
  (43, 'Quality Control Officer', 'Pharmaceuticals', 'Science', 'QC officers test raw materials and finished products at Square, Beximco, and other pharma companies.', '["GMP Standards","Lab Testing","Documentation","Analytical Chemistry","Attention to Detail"]'::jsonb, '[{"label":"QC Trainee","time":"0–2 yrs"},{"label":"QC Officer","time":"2–4 yrs","current":true},{"label":"Senior QC Officer","time":"4–7 yrs"},{"label":"QC Manager","time":"7–10 yrs"},{"label":"Quality Director","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 65,000–120,000'),
  (44, 'Environmental Scientist', 'Environment', 'Science', 'Environmental scientists work on conservation, pollution monitoring, and climate change projects.', '["Field Sampling","Data Analysis","Environmental Laws","Report Writing","GIS"]'::jsonb, '[{"label":"Field Assistant","time":"0–2 yrs"},{"label":"Environmental Scientist","time":"2–4 yrs","current":true},{"label":"Senior Scientist","time":"4–7 yrs"},{"label":"Project Manager","time":"7–10 yrs"},{"label":"Director","time":"10+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 70,000–130,000'),
  (45, 'Microbiologist', 'Microbiology', 'Science', 'Microbiologists work in food safety, pharmaceutical labs, and clinical diagnostics.', '["Culture Techniques","Sterilization","Microscopy","Lab Safety","Data Recording"]'::jsonb, '[{"label":"Lab Technician","time":"0–2 yrs"},{"label":"Microbiologist","time":"2–4 yrs","current":true},{"label":"Senior Microbiologist","time":"4–7 yrs"},{"label":"Lab Manager","time":"7–10 yrs"},{"label":"Scientific Director","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 65,000–120,000'),
  (46, 'Food Scientist', 'Food', 'Science', 'Food scientists develop new food products, ensure safety, and improve quality for food companies.', '["Food Safety","Product Development","Quality Assurance","Sensory Evaluation","Regulations"]'::jsonb, '[{"label":"Quality Trainee","time":"0–2 yrs"},{"label":"Food Scientist","time":"2–4 yrs","current":true},{"label":"Senior Food Scientist","time":"4–7 yrs"},{"label":"R&D Manager","time":"7–10 yrs"},{"label":"Technical Director","time":"10+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 70,000–130,000'),
  (47, 'Genetic Counselor', 'Genetics', 'Science', 'Genetic counselors work in hospitals and diagnostic labs, advising patients on genetic conditions.', '["Genetics Knowledge","Patient Counseling","Risk Assessment","Medical Ethics","Communication"]'::jsonb, '[{"label":"Genetic Assistant","time":"0–2 yrs"},{"label":"Genetic Counselor","time":"2–4 yrs","current":true},{"label":"Senior Counselor","time":"4–7 yrs"},{"label":"Clinic Manager","time":"7–10 yrs"},{"label":"Director of Genetics","time":"10+ yrs"}]'::jsonb, 'BDT 30,000–50,000', 'BDT 90,000–160,000'),
  (48, 'Agronomist', 'Agriculture', 'Science', 'Agronomists work in agricultural research, crop management, and farming advisory services.', '["Crop Science","Soil Management","Pest Control","Field Research","Farmer Training"]'::jsonb, '[{"label":"Field Officer","time":"0–2 yrs"},{"label":"Agronomist","time":"2–4 yrs","current":true},{"label":"Senior Agronomist","time":"4–7 yrs"},{"label":"Agriculture Manager","time":"7–10 yrs"},{"label":"Director of Agriculture","time":"10+ yrs"}]'::jsonb, 'BDT 18,000–32,000', 'BDT 60,000–110,000'),
  (49, 'Fisheries Officer', 'Fisheries', 'Science', 'Fisheries officers work in aquaculture, fishery management, and marine conservation.', '["Aquaculture","Fish Health","Water Quality","Stock Assessment","Regulatory Compliance"]'::jsonb, '[{"label":"Fisheries Assistant","time":"0–2 yrs"},{"label":"Fisheries Officer","time":"2–4 yrs","current":true},{"label":"Senior Officer","time":"4–7 yrs"},{"label":"Fisheries Manager","time":"7–10 yrs"},{"label":"Director of Fisheries","time":"10+ yrs"}]'::jsonb, 'BDT 18,000–32,000', 'BDT 60,000–110,000'),
  (50, 'Clinical Research Coordinator', 'Clinical Research', 'Science', 'CRCs manage clinical trials for pharmaceutical companies and research hospitals.', '["GCP Guidelines","Patient Recruitment","Data Collection","Regulatory Compliance","Ethics"]'::jsonb, '[{"label":"CRC Trainee","time":"0–2 yrs"},{"label":"Clinical Research Coordinator","time":"2–4 yrs","current":true},{"label":"Senior CRC","time":"4–7 yrs"},{"label":"Clinical Project Manager","time":"7–10 yrs"},{"label":"Clinical Operations Director","time":"10+ yrs"}]'::jsonb, 'BDT 30,000–50,000', 'BDT 90,000–170,000'),
  (51, 'Content Writer', 'Media', 'Arts', 'Content writers create articles, blogs, and social media content for digital agencies and media houses.', '["Creative Writing","SEO","Research","Grammar","Content Strategy"]'::jsonb, '[{"label":"Junior Writer","time":"0–1 yr"},{"label":"Content Writer","time":"1–3 yrs","current":true},{"label":"Senior Writer","time":"3–5 yrs"},{"label":"Content Manager","time":"5–8 yrs"},{"label":"Editorial Director","time":"8+ yrs"}]'::jsonb, 'BDT 18,000–30,000', 'BDT 50,000–90,000'),
  (52, 'Graphic Designer', 'Design', 'Arts', 'Graphic designers create visual content for brands, advertising agencies, and digital media.', '["Adobe Photoshop","Illustrator","Typography","Branding","Figma"]'::jsonb, '[{"label":"Junior Designer","time":"0–1 yr"},{"label":"Graphic Designer","time":"1–3 yrs","current":true},{"label":"Senior Designer","time":"3–5 yrs"},{"label":"Art Director","time":"5–8 yrs"},{"label":"Creative Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 60,000–120,000'),
  (53, 'Journalist', 'News', 'Arts', 'Journalists report news for newspapers, TV channels, and online news portals in Bangladesh.', '["Reporting","Interviewing","Fact-Checking","Writing","Ethics"]'::jsonb, '[{"label":"Reporter","time":"0–1 yr"},{"label":"Journalist","time":"1–3 yrs","current":true},{"label":"Senior Reporter","time":"3–5 yrs"},{"label":"News Editor","time":"5–8 yrs"},{"label":"Editor-in-Chief","time":"8+ yrs"}]'::jsonb, 'BDT 15,000–25,000', 'BDT 50,000–100,000'),
  (54, 'Public Relations Officer', 'PR', 'Arts', 'PROs manage media relations, press releases, and corporate communications for companies.', '["Media Relations","Press Release Writing","Crisis Communication","Event Planning","Networking"]'::jsonb, '[{"label":"PR Assistant","time":"0–1 yr"},{"label":"PRO","time":"1–3 yrs","current":true},{"label":"Senior PRO","time":"3–5 yrs"},{"label":"PR Manager","time":"5–8 yrs"},{"label":"Communications Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 70,000–140,000'),
  (55, 'Social Media Manager', 'Digital Marketing', 'Arts', 'Social media managers plan and execute social media strategies for brands and agencies.', '["Instagram/Facebook/LinkedIn","Content Calendar","Analytics","Community Management","Canva"]'::jsonb, '[{"label":"Social Media Assistant","time":"0–1 yr"},{"label":"Social Media Manager","time":"1–3 yrs","current":true},{"label":"Senior Manager","time":"3–5 yrs"},{"label":"Head of Social","time":"5–8 yrs"},{"label":"Digital Marketing Director","time":"8+ yrs"}]'::jsonb, 'BDT 18,000–32,000', 'BDT 60,000–120,000'),
  (56, 'Photographer / Videographer', 'Media', 'Arts', 'Photographers and videographers work in media houses, wedding photography, and creative agencies.', '["Photography","Video Editing","Lighting","Adobe Suite","Storytelling"]'::jsonb, '[{"label":"Assistant Photographer","time":"0–1 yr"},{"label":"Photographer","time":"1–3 yrs","current":true},{"label":"Senior Photographer","time":"3–5 yrs"},{"label":"Creative Lead","time":"5–8 yrs"},{"label":"Director of Photography","time":"8+ yrs"}]'::jsonb, 'BDT 15,000–28,000', 'BDT 50,000–100,000'),
  (57, 'UX/UI Designer', 'Tech Design', 'Arts', 'UX/UI designers create user-friendly interfaces for websites and mobile apps.', '["Figma","User Research","Wireframing","Prototyping","Usability Testing"]'::jsonb, '[{"label":"Junior Designer","time":"0–1 yr"},{"label":"UX/UI Designer","time":"1–3 yrs","current":true},{"label":"Senior Designer","time":"3–5 yrs"},{"label":"Design Lead","time":"5–8 yrs"},{"label":"Head of Design","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–45,000', 'BDT 90,000–180,000'),
  (58, 'Event Manager', 'Events', 'Arts', 'Event managers plan and execute corporate events, weddings, and conferences.', '["Event Planning","Vendor Management","Budgeting","Logistics","Client Communication"]'::jsonb, '[{"label":"Event Coordinator","time":"0–1 yr"},{"label":"Event Manager","time":"1–3 yrs","current":true},{"label":"Senior Manager","time":"3–5 yrs"},{"label":"Event Director","time":"5–8 yrs"},{"label":"Head of Events","time":"8+ yrs"}]'::jsonb, 'BDT 18,000–32,000', 'BDT 60,000–120,000'),
  (59, 'Translator (English-Bangla)', 'Translation', 'Arts', 'Translators work in publishing, media, and international organisations.', '["English Fluency","Bangla Writing","Translation Tools","Proofreading","Cultural Knowledge"]'::jsonb, '[{"label":"Translator","time":"0–2 yrs","current":true},{"label":"Senior Translator","time":"2–4 yrs"},{"label":"Translation Editor","time":"4–6 yrs"},{"label":"Language Lead","time":"6–8 yrs"},{"label":"Localization Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 60,000–110,000'),
  (60, 'Copywriter', 'Advertising', 'Arts', 'Copywriters create advertising copy for brands, agencies, and marketing campaigns.', '["Creative Writing","Brand Voice","Headlines","Storytelling","Campaign Strategy"]'::jsonb, '[{"label":"Junior Copywriter","time":"0–1 yr"},{"label":"Copywriter","time":"1–3 yrs","current":true},{"label":"Senior Copywriter","time":"3–5 yrs"},{"label":"Copy Chief","time":"5–8 yrs"},{"label":"Creative Director","time":"8+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 70,000–140,000'),
  (61, 'School Teacher', 'Education', 'Education', 'School teachers work in private and public schools across Bangladesh, teaching primary or secondary students.', '["Lesson Planning","Classroom Management","Subject Expertise","Communication","Patience"]'::jsonb, '[{"label":"Assistant Teacher","time":"0–2 yrs"},{"label":"Teacher","time":"2–4 yrs","current":true},{"label":"Senior Teacher","time":"4–7 yrs"},{"label":"Department Head","time":"7–10 yrs"},{"label":"Principal","time":"10+ yrs"}]'::jsonb, 'BDT 15,000–25,000', 'BDT 50,000–100,000'),
  (62, 'Education Program Officer', 'NGO', 'Education', 'Program officers design and manage education initiatives for NGOs like BRAC and Save the Children.', '["Project Management","Monitoring & Evaluation","Report Writing","Community Engagement","Data Analysis"]'::jsonb, '[{"label":"Program Assistant","time":"0–1 yr"},{"label":"Program Officer","time":"1–3 yrs","current":true},{"label":"Senior Officer","time":"3–5 yrs"},{"label":"Program Manager","time":"5–8 yrs"},{"label":"Director","time":"8+ yrs"}]'::jsonb, 'BDT 25,000–40,000', 'BDT 70,000–120,000'),
  (63, 'Curriculum Developer', 'EdTech', 'Education', 'Curriculum developers create learning materials, syllabi, and assessments for schools and edtech companies.', '["Curriculum Design","Educational Theory","Content Writing","Assessment Design","Research"]'::jsonb, '[{"label":"Curriculum Assistant","time":"0–2 yrs"},{"label":"Curriculum Developer","time":"2–4 yrs","current":true},{"label":"Senior Developer","time":"4–7 yrs"},{"label":"Curriculum Manager","time":"7–10 yrs"},{"label":"Head of Curriculum","time":"10+ yrs"}]'::jsonb, 'BDT 25,000–40,000', 'BDT 80,000–150,000'),
  (64, 'Educational Counsellor', 'Counselling', 'Education', 'Educational counsellors advise students on career paths, university admissions, and study abroad options.', '["Counselling","Career Guidance","University Admissions","Communication","Problem Solving"]'::jsonb, '[{"label":"Counselling Assistant","time":"0–2 yrs"},{"label":"Educational Counsellor","time":"2–4 yrs","current":true},{"label":"Senior Counsellor","time":"4–7 yrs"},{"label":"Head Counsellor","time":"7–10 yrs"},{"label":"Director of Student Services","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 60,000–110,000'),
  (65, 'Instructional Designer', 'EdTech', 'Education', 'Instructional designers create online courses, e-learning modules, and training materials.', '["E-learning Tools","Articulate Storyline","Instructional Design Models","Multimedia","Assessment"]'::jsonb, '[{"label":"Junior ID","time":"0–2 yrs"},{"label":"Instructional Designer","time":"2–4 yrs","current":true},{"label":"Senior ID","time":"4–7 yrs"},{"label":"Learning Experience Manager","time":"7–10 yrs"},{"label":"Head of Learning Design","time":"10+ yrs"}]'::jsonb, 'BDT 25,000–45,000', 'BDT 80,000–160,000'),
  (66, 'University Lecturer', 'Higher Education', 'Education', 'University lecturers teach undergraduate courses and conduct research in their subject area.', '["Teaching","Research","Academic Writing","Public Speaking","Subject Mastery"]'::jsonb, '[{"label":"Lecturer","time":"0–3 yrs","current":true},{"label":"Senior Lecturer","time":"3–6 yrs"},{"label":"Assistant Professor","time":"6–9 yrs"},{"label":"Associate Professor","time":"9–12 yrs"},{"label":"Professor","time":"12+ yrs"}]'::jsonb, 'BDT 35,000–55,000', 'BDT 80,000–150,000'),
  (67, 'Special Education Teacher', 'Special Education', 'Education', 'Special education teachers work with students who have learning disabilities, physical disabilities, or other special needs.', '["Individualized Education Plans","Behaviour Management","Assistive Technology","Patience","Adaptation"]'::jsonb, '[{"label":"Special Ed Assistant","time":"0–2 yrs"},{"label":"Special Ed Teacher","time":"2–4 yrs","current":true},{"label":"Senior Teacher","time":"4–7 yrs"},{"label":"Special Ed Coordinator","time":"7–10 yrs"},{"label":"Director of Special Education","time":"10+ yrs"}]'::jsonb, 'BDT 20,000–35,000', 'BDT 60,000–120,000'),
  (68, 'Education Technology Specialist', 'EdTech', 'Education', 'EdTech specialists implement technology solutions in schools and educational institutions.', '["LMS Management","Teacher Training","Technical Support","Educational Technology","Project Management"]'::jsonb, '[{"label":"EdTech Assistant","time":"0–2 yrs"},{"label":"EdTech Specialist","time":"2–4 yrs","current":true},{"label":"Senior Specialist","time":"4–7 yrs"},{"label":"EdTech Manager","time":"7–10 yrs"},{"label":"Director of Digital Learning","time":"10+ yrs"}]'::jsonb, 'BDT 25,000–45,000', 'BDT 80,000–160,000'),
  (69, 'Training Coordinator', 'Corporate Training', 'Education', 'Training coordinators organise employee training programs for corporations and NGOs.', '["Training Logistics","Needs Assessment","Vendor Management","Budgeting","Communication"]'::jsonb, '[{"label":"Training Assistant","time":"0–2 yrs"},{"label":"Training Coordinator","time":"2–4 yrs","current":true},{"label":"Training Manager","time":"4–7 yrs"},{"label":"Learning & Development Manager","time":"7–10 yrs"},{"label":"Chief Learning Officer","time":"10+ yrs"}]'::jsonb, 'BDT 22,000–38,000', 'BDT 70,000–130,000'),
  (70, 'Early Childhood Educator', 'Early Education', 'Education', 'Early childhood educators work in preschools and kindergartens, teaching children aged 3-6 years.', '["Child Development","Play-based Learning","Classroom Management","Parent Communication","Creativity"]'::jsonb, '[{"label":"Assistant Teacher","time":"0–2 yrs"},{"label":"Lead Teacher","time":"2–4 yrs","current":true},{"label":"Senior Teacher","time":"4–7 yrs"},{"label":"Preschool Director","time":"7–10 yrs"},{"label":"Early Childhood Consultant","time":"10+ yrs"}]'::jsonb, 'BDT 15,000–25,000', 'BDT 50,000–90,000')
ON CONFLICT (id) DO NOTHING;

-- resources (42 rows, English only; *_bn left NULL)
-- Ids are assigned explicitly here: the source JSON had none, but the table
-- needs a stable key for ON CONFLICT idempotency and for admin edit/delete.
-- Note: the 42 rows reference only 23 distinct URLs — several guides are
-- deliberately listed against more than one discipline or category.
INSERT INTO resources (id, title_en, title_bn, description_en, description_bn, type, discipline, category, url) VALUES
  (1, 'How to write a strong CV for finance roles in Bangladesh', NULL, 'A step-by-step guide to structuring your CV for Bangladeshi finance employers, including what local recruiters look for.', NULL, 'Guide', 'Finance', 'Resume Writing', 'https://www.scribd.com/document/160183049/CV-Format-Final'),
  (2, 'Interview preparation guide for fresh graduates', NULL, 'Common interview question formats, expected behaviours, and how to present yourself confidently to Bangladeshi employers.', NULL, 'Article', 'All disciplines', 'Interview Prep', 'https://www.glassdoor.com.au/Interview/dhaka-civil-engineer-interview-questions-SRCH_IL.0,5_IS3812_KO6,20_SDRD.htm'),
  (3, 'Understanding Bangladesh job market trends 2026', NULL, 'A breakdown of which sectors are hiring, what skills are in demand, and how to position yourself effectively.', NULL, 'Article', 'All disciplines', 'Job Search', 'https://www.thedailystar.net/business/news/wb-support-job-creation-inclusive-growth-4130951'),
  (4, 'Soft skills in Asian professional culture — what employers expect', NULL, 'How professional soft skills differ between Asian and Western workplace cultures, and how to demonstrate them.', NULL, 'Video', 'All disciplines', 'Soft Skills', 'https://www.thedailystar.net/tech-startup/news/why-entrepreneurship-must-be-bangladeshs-next-national-mission-4108111'),
  (5, 'Building technical skills for software engineering roles', NULL, 'A curated learning path covering the technical skills most sought after by Bangladeshi tech companies.', NULL, 'Course', 'IT', 'Skill Development', 'https://codecamp.asthait.com/'),
  (6, 'How to write a cover letter for Bangladeshi employers', NULL, 'Cover letter conventions for the Bangladeshi job market, with structure, tone, and example phrases.', NULL, 'Guide', 'All disciplines', 'Resume Writing', 'https://bdjobscareer.blogspot.com/p/cover-letter.html'),
  (7, 'How to ace finance interviews at Bangladeshi banks', NULL, 'Common interview questions for Dutch-Bangla Bank, BRAC Bank, and City Bank, with sample answers and tips.', NULL, 'Video', 'Finance', 'Interview Prep', 'https://www.youtube.com/watch?v=ZBcPLf2UTx4'),
  (8, 'Top financial certifications for career growth in Bangladesh', NULL, 'CFA, ACCA, CIMA, and local certification options to boost your finance career.', NULL, 'Article', 'Finance', 'Skill Development', 'https://www.linkedin.com/pulse/top-financial-certifications-career-growth-bangladesh'),
  (9, 'Where to find finance jobs in Bangladesh', NULL, 'Top job portals, recruitment agencies, and company career pages for finance roles.', NULL, 'Guide', 'Finance', 'Job Search', 'https://bdjobs.com/h/jobs?fcatID=1'),
  (10, 'Soft skills every finance professional needs', NULL, 'Communication, negotiation, ethical judgment, and client relationship management.', NULL, 'Video', 'Finance', 'Soft Skills', 'https://www.youtube.com/watch?v=Q0Ychzwgfow'),
  (11, 'How to structure a finance CV for Bangladeshi employers', NULL, 'What recruiters at banks and financial institutions look for in a fresh graduate CV.', NULL, 'Guide', 'Finance', 'Resume Writing', 'https://www.scribd.com/document/160183049/CV-Format-Final'),
  (12, 'Technical interview preparation for software engineers', NULL, 'Data structures, algorithms, and system design questions commonly asked at Bangladeshi tech companies.', NULL, 'Video', 'IT', 'Interview Prep', 'https://www.youtube.com/watch?v=1NuTj6j3bU4'),
  (13, 'Best coding bootcamps and online courses for Bangladeshi students', NULL, 'Free and paid resources to learn programming, web development, and data science.', NULL, 'Article', 'IT', 'Skill Development', 'https://www.thedailystar.net/business/economy/news/govt-drafts-5-year-strategic-plan-4152386'),
  (14, 'How to find IT jobs at Bangladeshi startups', NULL, 'Networking strategies, job boards, and company research for tech roles.', NULL, 'Guide', 'IT', 'Job Search', 'https://startup.jobs/locations/bangladesh'),
  (15, 'Communication and teamwork in software development', NULL, 'Why soft skills matter for developers working in agile teams.', NULL, 'Article', 'IT', 'Soft Skills', 'https://codecamp.asthait.com/'),
  (16, 'How to write a developer CV that gets noticed', NULL, 'Highlighting projects, GitHub contributions, and technical skills effectively.', NULL, 'Video', 'IT', 'Resume Writing', 'https://www.youtube.com/watch?v=gaxcx9g54c8'),
  (17, 'Interview tips for research assistant positions', NULL, 'What icddr,b, BARI, and university labs look for in fresh science graduates.', NULL, 'Guide', 'Science', 'Interview Prep', 'https://github.com/TamimEhsan/interview-questions-bangladesh'),
  (18, 'Essential lab techniques every science graduate should know', NULL, 'Microscopy, PCR, chromatography, and other lab skills for research roles.', NULL, 'PDF', 'Science', 'Skill Development', 'https://microbiologysociety.org/static/uploaded/23cbf9c5-f8c8-4f91-b092a4ad819e6357.pdf'),
  (19, 'Career paths for science graduates beyond research', NULL, 'Pharmaceuticals, quality control, environmental monitoring, and teaching.', NULL, 'Article', 'Science', 'Job Search', 'https://www.thedailystar.net/news/bangladesh/news/imf-staff-report-educated-youth-return-farms-job-market-falters-4132331'),
  (20, 'Scientific writing and publishing for early career researchers', NULL, 'How to write research papers, grant proposals, and literature reviews.', NULL, 'Video', 'Science', 'Soft Skills', 'https://www.youtube.com/watch?v=ZBcPLf2UTx4'),
  (21, 'How to write a research CV for science roles', NULL, 'Highlighting publications, lab experience, and technical skills.', NULL, 'Guide', 'Science', 'Resume Writing', 'https://github.com/TamimEhsan/interview-questions-bangladesh'),
  (22, 'Common engineering interview questions in Bangladesh', NULL, 'Technical and behavioural questions for civil, electrical, and mechanical engineering roles.', NULL, 'Guide', 'Engineering', 'Interview Prep', 'https://www.glassdoor.com.au/Interview/dhaka-civil-engineer-interview-questions-SRCH_IL.0,5_IS3812_KO6,20_SDRD.htm'),
  (23, 'Must-have software skills for engineers', NULL, 'AutoCAD, SolidWorks, MATLAB, and other tools used in Bangladeshi industries.', NULL, 'Course', 'Engineering', 'Skill Development', 'https://www.epicflow.com/blog/engineering-project-management-the-essential-guide/'),
  (24, 'Engineering job opportunities in government and private sectors', NULL, 'How to apply for roles at LGED, RAJUK, power plants, and construction firms.', NULL, 'Article', 'Engineering', 'Job Search', 'https://www.ilo.org/publications/reviving-and-reconnecting-economic-growth-and-employment-bangladesh'),
  (25, 'Project management skills for engineers', NULL, 'Leadership, budgeting, client communication, and team coordination.', NULL, 'Video', 'Engineering', 'Soft Skills', 'https://www.youtube.com/watch?v=Q0Ychzwgfow'),
  (26, 'How to write an engineering CV that stands out', NULL, 'Highlighting projects, internships, and technical certifications.', NULL, 'Guide', 'Engineering', 'Resume Writing', 'https://www.scribd.com/document/160183049/CV-Format-Final'),
  (27, 'How to prepare for marketing and sales interviews', NULL, 'Common questions for Grameenphone, Unilever, and other top employers.', NULL, 'Video', 'Business', 'Interview Prep', 'https://www.youtube.com/watch?v=Q0Ychzwgfow'),
  (28, 'Digital marketing skills every business graduate needs', NULL, 'SEO, social media marketing, Google Ads, and email marketing basics.', NULL, 'Course', 'Business', 'Skill Development', 'https://sudoksho.com/course-overview/85/guide-to-digital-marketing-platforms'),
  (29, 'Where to find business jobs in Bangladesh', NULL, 'Top companies, job portals, and networking events for business graduates.', NULL, 'Article', 'Business', 'Job Search', 'https://www.linkedin.com/jobs/business-development-executive-jobs-dhaka/'),
  (30, 'Negotiation and persuasion skills for business professionals', NULL, 'How to negotiate salary, close deals, and influence stakeholders.', NULL, 'Guide', 'Business', 'Soft Skills', 'https://www.thedailystar.net/supplements-0/news/bangladesh-doesnt-have-job-crisis-it-has-matching-crisis-4115356'),
  (31, 'How to write a business CV for corporate roles', NULL, 'Structuring experience, achievements, and leadership examples.', NULL, 'Guide', 'Business', 'Resume Writing', 'https://www.scribd.com/document/160183049/CV-Format-Final'),
  (32, 'Portfolio preparation for creative job interviews', NULL, 'How to present your design, writing, or photography portfolio to employers.', NULL, 'Video', 'Arts', 'Interview Prep', 'https://www.youtube.com/watch?v=Q0Ychzwgfow'),
  (33, 'Skills you need for media and creative careers', NULL, 'Graphic design, video editing, content writing, and social media management.', NULL, 'Article', 'Arts', 'Skill Development', 'https://www.thedailystar.net/tech-startup/news/why-entrepreneurship-must-be-bangladeshs-next-national-mission-4108111'),
  (34, 'Freelancing and remote work opportunities for arts graduates', NULL, 'Platforms, pricing, and building a freelance career from Bangladesh.', NULL, 'Guide', 'Arts', 'Job Search', 'https://www.youtube.com/watch?v=Q0Ychzwgfow'),
  (35, 'Creative thinking and storytelling in the workplace', NULL, 'How to use creativity to solve problems and communicate ideas.', NULL, 'Course', 'Arts', 'Soft Skills', 'https://www.epicflow.com/blog/engineering-project-management-the-essential-guide/'),
  (36, 'How to write a CV for creative roles', NULL, 'Balancing creativity with professionalism in your job application.', NULL, 'Guide', 'Arts', 'Resume Writing', 'https://bdjobscareer.blogspot.com/p/cover-letter.html'),
  (37, 'How to prepare for teaching job interviews', NULL, 'Demonstration lessons, classroom management questions, and school expectations.', NULL, 'Guide', 'Education', 'Interview Prep', 'https://www.youtube.com/watch?v=ZBcPLf2UTx4'),
  (38, 'Professional development for teachers in Bangladesh', NULL, 'Workshops, certifications, and online courses to advance your teaching career.', NULL, 'Article', 'Education', 'Skill Development', 'https://www.thedailystar.net/supplements-0/news/project-prometheus-and-the-future-labour-implications-bangladeshs-low-cost-labour-economy-4161661'),
  (39, 'Where to find teaching jobs in Bangladesh', NULL, 'International schools, government colleges, NGOs, and tutoring platforms.', NULL, 'Guide', 'Education', 'Job Search', 'https://bdjobs.com/h/jobs?fcatID=1'),
  (40, 'Classroom management and communication skills', NULL, 'Building rapport with students, parents, and colleagues.', NULL, 'Video', 'Education', 'Soft Skills', 'https://www.youtube.com/watch?v=1NuTj6j3bU4'),
  (41, 'How to write a CV for teaching positions', NULL, 'Highlighting teaching experience, certifications, and subject expertise.', NULL, 'Guide', 'Education', 'Resume Writing', 'https://bdjobscareer.blogspot.com/p/cover-letter.html'),
  (42, 'How to network as a fresh graduate in Bangladesh', NULL, 'LinkedIn tips, industry events, and building professional connections locally.', NULL, 'Video', 'All disciplines', 'Job Search', 'https://www.youtube.com/watch?v=Q0Ychzwgfow')
ON CONFLICT (id) DO NOTHING;

-- alumni (10 rows)
INSERT INTO alumni (id, full_name, institution, discipline, graduation_year, "current_role", industry, bio, image_initials, consent_given, is_published) VALUES
  (1, 'Sadia Rahman', 'BUET', 'Engineering', 2022, 'Software Engineer', 'Technology', 'Sadia works at Pathao as a backend developer. She specializes in Node.js and microservices architecture. During university, she led the BUET Coding Club and interned at SELISE Digital Platforms.', 'SR', TRUE, TRUE),
  (2, 'Rakib Hasan', 'North South University', 'Finance', 2021, 'Financial Analyst', 'Banking and Finance', 'Rakib is a Financial Analyst at BRAC Bank. He completed his CFA Level 2 and previously interned at Standard Chartered Bank. He advises students to focus on financial modeling and Excel skills.', 'RH', TRUE, TRUE),
  (3, 'Tania Akter', 'University of Dhaka', 'Science', 2020, 'Research Associate', 'Research', 'Tania works at icddr,b as a Research Associate in the Infectious Diseases division. She has co-authored 3 research papers and is pursuing her Master''s in Public Health.', 'TA', TRUE, TRUE),
  (4, 'Mehedi Islam', 'RUET', 'Engineering', 2019, 'Project Manager', 'Construction', 'Mehedi manages infrastructure projects at Rangs Properties Ltd. He has overseen 5 major residential projects in Dhaka and specializes in project planning and cost estimation.', 'MI', TRUE, TRUE),
  (5, 'Nusrat Jahan', 'University of Chittagong', 'Business', 2021, 'Marketing Executive', 'Marketing', 'Nusrat works at Unilever Bangladesh as a Brand Executive. She manages the Lifebuoy brand and has led successful digital campaigns reaching millions of customers.', 'NJ', TRUE, TRUE),
  (6, 'Arif Chowdhury', 'IUB', 'IT', 2022, 'Frontend Developer', 'Technology', 'Arif is a Frontend Developer at Shohoz. He is passionate about React and building user-friendly interfaces. He also mentors students at his former university.', 'AC', TRUE, TRUE),
  (7, 'Farzana Haque', 'Jahangirnagar University', 'Arts', 2020, 'Content Strategist', 'Media', 'Farzana leads content strategy at The Daily Star''s digital wing. She creates engaging content for social media and has grown their Instagram following to 500k.', 'FH', TRUE, TRUE),
  (8, 'Shahid Khan', 'BRAC University', 'Business', 2021, 'Management Trainee', 'Management', 'Shahid is a Management Trainee at Grameenphone. He is rotating through different departments including sales, marketing, and operations as part of the MT program.', 'SK', TRUE, TRUE),
  (9, 'Moumita Das', 'BUET', 'Engineering', 2022, 'Civil Engineer', 'Construction', 'Moumita works at LGED as a Junior Engineer. She has worked on rural road development projects in 3 districts and is passionate about sustainable infrastructure.', 'MD', TRUE, TRUE),
  (10, 'Imran Hossain', 'University of Dhaka', 'Science', 2020, 'Quality Control Officer', 'Pharmaceuticals', 'Imran works at Square Pharmaceuticals in quality control. He ensures products meet GMP standards and has contributed to 3 successful product launches.', 'IH', TRUE, TRUE)
ON CONFLICT (id) DO NOTHING;

-- Re-sync SERIAL sequences past the explicitly-seeded ids.
SELECT setval('disciplines_id_seq',  (SELECT COALESCE(MAX(id), 1) FROM disciplines));
SELECT setval('career_paths_id_seq', (SELECT COALESCE(MAX(id), 1) FROM career_paths));
SELECT setval('resources_id_seq',    (SELECT COALESCE(MAX(id), 1) FROM resources));
SELECT setval('alumni_id_seq',       (SELECT COALESCE(MAX(id), 1) FROM alumni));
